#!/usr/bin/env python3
"""Stage 7 acceptance scenario: the unchanged-consumer substitution matrix.

The consumer source under `consumer/` is frozen: one copy, hashed once, compiled
into every arm. The only thing that varies per arm is **which revision of C1 and
C2 the consumer's dependencies resolve to**:

    arm        C1            C2
    baseline   baseline      baseline
    c1-only    candidate     baseline
    c2-only    baseline      candidate
    combined   candidate     candidate

Each arm gets its own revision tree under `--root`, because a mixed arm needs one
`layerfs-telemetry` in its graph (the crate is byte-identical in both revisions,
so it is materialized once per tree from the repository).

Nothing is patched, vendored or forked: the arms differ only in path selection,
and the consumer is never edited. Revisions are materialized from git, so the
matrix is reproducible from this directory alone.

Usage:
  run.py --baseline <rev-or-path> --candidate <rev-or-path> [--root /tmp/subst] [--out matrix.json]
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import json
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
CRATES = ("layerfs-telemetry", "layerfs-content", "layerfs-storage")
ARMS = {
    "baseline": ("baseline", "baseline"),
    "c1-only": ("candidate", "baseline"),
    "c2-only": ("baseline", "candidate"),
    "combined": ("candidate", "candidate"),
}
MANIFEST = '''# Substitution arm: {arm}   (generated by run.py; the record is matrix.json)
#
# The consumer source is frozen and shared (`../../consumer/`); the only difference
# between the four arms is which revision each product dependency resolves to.
# No [patch], no vendoring, no third-party modification, no consumer edit.

[package]
name = "substitution-{pkg}"
version = "0.0.0"
edition = "2021"
rust-version = "1.85"
publish = false

[workspace]

[dependencies]
layerfs-content = {{ path = "{tree}/crates/layerfs-content" }}
layerfs-storage = {{ path = "{tree}/crates/layerfs-storage" }}
layerfs-telemetry = {{ path = "{tree}/crates/layerfs-telemetry" }}
rusqlite = {{ version = "=0.40.2", features = ["cache", "hooks", "trace", "limits", "blob"] }}

[[test]]
name = "core_pipeline"
path = "../../consumer/core_pipeline.rs"

[[example]]
name = "filesystem_primitives_candidate"
path = "../../consumer/filesystem_primitives_candidate.rs"

[[bin]]
name = "cross_revision"
path = "../../consumer/cross_revision.rs"
'''


def sh(*command: str, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(command, capture_output=True, text=True, **kwargs)


def resolve(revision: str) -> Path:
    """A revision is either an existing checkout or a git revision to materialize."""
    path = Path(revision)
    if path.is_dir():
        return path
    worktree = Path("/tmp/subst-revisions") / revision
    if not worktree.is_dir():
        worktree.parent.mkdir(parents=True, exist_ok=True)
        result = sh("git", "-C", str(REPO), "worktree", "add", "--detach", str(worktree), revision)
        if result.returncode != 0:
            raise SystemExit(f"git worktree add {revision}: {result.stderr.strip()}")
    return worktree


def commit_of(checkout: Path) -> str:
    return sh("git", "-C", str(checkout), "rev-parse", "HEAD").stdout.strip()


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def materialize(root: Path, arm: str, revisions: dict[str, Path]) -> Path:
    tree = root / arm
    if tree.exists():
        shutil.rmtree(tree)
    (tree / "crates").mkdir(parents=True)
    shutil.copy2(REPO / "core" / "Cargo.toml", tree / "Cargo.toml")
    shutil.copy2(REPO / "core" / "Cargo.lock", tree / "Cargo.lock")
    # telemetry is byte-identical in both revisions; it comes from the repository
    # so that a mixed arm still has exactly one copy in its graph.
    for crate, side in zip(CRATES, ("head", *ARMS[arm])):
        source = (REPO if side == "head" else revisions[side]) / "core" / "crates" / crate
        shutil.copytree(source, tree / "crates" / crate,
                        ignore=shutil.ignore_patterns("target", "*.pyc"))
    return tree


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline", required=True)
    parser.add_argument("--candidate", required=True)
    parser.add_argument("--root", default="/tmp/subst")
    parser.add_argument("--out", default=str(HERE / "matrix.json"))
    arguments = parser.parse_args()

    revisions = {"baseline": resolve(arguments.baseline), "candidate": resolve(arguments.candidate)}
    revisions["head"] = REPO
    commits = {"baseline": commit_of(revisions["baseline"]), "candidate": commit_of(revisions["candidate"])}

    consumer = sorted(p for p in (HERE / "consumer").rglob("*") if p.is_file())
    consumer_digests = {str(p.relative_to(HERE)): digest(p) for p in consumer}

    root = Path(arguments.root)
    matrix: dict[str, object] = {
        "schema": "layerfs-substitution-matrix-v1",
        "baseline_revision": commits["baseline"],
        "candidate_revision": commits["candidate"],
        "consumer_source": consumer_digests,
        "arms": {},
    }
    for arm, (c1_side, c2_side) in ARMS.items():
        tree = materialize(root, arm, revisions)
        manifest = HERE / "arms" / arm / "Cargo.toml"
        manifest.write_text(MANIFEST.format(arm=arm, pkg=arm.replace("-", "_"), tree=tree))
        arm_record: dict[str, object] = {
            "c1": commits[c1_side] if c1_side != "head" else commits["candidate"],
            "c2": commits[c2_side] if c2_side != "head" else commits["candidate"],
            "c1_source": c1_side, "c2_source": c2_side,
            "manifest_sha256": digest(manifest),
            "tree": str(tree),
        }
        # The materialized crates must be the revision's crates, byte for byte.
        for crate, side in zip(CRATES[1:], (c1_side, c2_side)):
            source = (REPO if side == "head" else revisions[side]) / "core" / "crates" / crate
            live = tree / "crates" / crate
            differing = [
                str(p.relative_to(source)) for p in source.rglob("*.rs")
                if p.is_file() and (not (live / p.relative_to(source)).exists()
                                    or digest(p) != digest(live / p.relative_to(source)))
            ]
            arm_record[f"{crate}_differs_from_revision"] = differing
        environment = {"CARGO_TARGET_DIR": str(root / "target")}
        test = sh("cargo", "+1.85.1", "test", "--manifest-path", str(manifest), env={**os.environ, **environment})
        arm_record["test"] = {
            "exit_code": test.returncode,
            "passed": "test result: ok" in test.stdout,
            "tail": (test.stdout + test.stderr).strip().splitlines()[-3:],
        }
        example = sh("cargo", "+1.85.1", "run", "--quiet", "--manifest-path", str(manifest),
                     "--example", "filesystem_primitives_candidate", "--",
                     "--files", "2000", "--changes", "200", "--samples", "1", env={**os.environ, **environment})
        stdout = example.stdout.strip().splitlines()
        # The example prints both identity and one timing field; only identity is
        # compared across arms, so the elapsed field is stripped from the record.
        identity = [re.sub(r"elapsed_ns \d+", "elapsed_ns <elapsed>", line) for line in stdout]
        arm_record["example"] = {
            "exit_code": example.returncode,
            "stdout": stdout,
            "identity_lines": identity,
        }
        matrix["arms"][arm] = arm_record
        print(f"{arm:9s} test={'ok' if arm_record['test']['passed'] else 'FAILED'} "
              f"example={'ok' if example.returncode == 0 else 'FAILED'}", flush=True)

    # Cross-revision persisted-data checks: create the Store under one arm and read
    # it under another. A refusal is recorded with its typed error and exit code.
    workdir = root / "cross"
    workdir.mkdir(parents=True, exist_ok=True)

    def arm_binary(arm: str, *arguments: str) -> subprocess.CompletedProcess:
        return sh("cargo", "+1.85.1", "run", "--quiet", "--manifest-path",
                  str(HERE / "arms" / arm / "Cargo.toml"), "--bin", "cross_revision",
                  "--", *arguments, env={**os.environ, "CARGO_TARGET_DIR": str(root / "target")})

    checks = (
        ("baseline-create->baseline-read", "baseline", "baseline"),
        ("candidate-create->candidate-read", "combined", "combined"),
        ("baseline-create->candidate-read", "baseline", "combined"),
        ("candidate-create->baseline-read", "combined", "baseline"),
    )
    cross: dict[str, object] = {}
    for name, writer, reader in checks:
        store = workdir / (name.replace("->", "_to_") + ".sqlite")
        if store.exists():
            store.unlink()
        created = arm_binary(writer, "create", str(store))
        words = created.stdout.split()
        root_id = words[words.index("root") + 1] if "root" in words else ""
        opened = arm_binary(reader, "read", str(store), root_id) if root_id else None
        cross[name] = {
            "root": root_id,
            "writer": writer,
            "reader": reader,
            "create_exit_code": created.returncode,
            "create_stdout": created.stdout.strip(),
            "read_exit_code": None if opened is None else opened.returncode,
            "read_stdout": "" if opened is None else opened.stdout.strip(),
            "read_refused": bool(opened is not None and opened.returncode == 3),
        }
        print(f"{name:34s} create={created.returncode} read={cross[name]['read_exit_code']} "
              f"{cross[name]['read_stdout'][:60]}", flush=True)
    matrix["cross_revision"] = cross

    baseline_identity = matrix["arms"]["baseline"]["example"]["identity_lines"]
    matrix["canonical_identity"] = {
        "lines_compared": len(baseline_identity),
        "identical_in_every_arm": all(
            record["example"]["identity_lines"] == baseline_identity
            for record in matrix["arms"].values()
        ),
        "baseline": baseline_identity,
    }
    matrix["test_passed_in_every_arm"] = all(
        record["test"]["passed"] for record in matrix["arms"].values()
    )
    Path(arguments.out).write_text(json.dumps(matrix, indent=2, sort_keys=True) + "\n")
    print(f"matrix -> {arguments.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
