"""Coverage classification of the four predecessors that carry pinned-view code (O-10)."""

VIEW = "Pinned read-only SDK view leases. Not covered by any active crate; whether the product keeps them is the unanswered owner question O-10 (303/08 K20, §4.2, §7)"

# ---------------------------------------------------------------- SDK predecessor
SDK_SRC = {
    "src/lib.rs": ("A+C", "Exports of ProjectApi, SandboxApi, WorkspaceApi and the composed Server", "`layerfs-api/sdk/src/lib.rs`; the Server re-export is retired [D1]"),
    "src/project.rs": ("A+C", "Project Init and Branch fork through the composed Server", "Server route [D1]. `ProjectApi::init`, `install`, `fork`, `history`: K `init.rs` (2), D `native_install.rs` (3), D `native_control.rs::native_mount_commit_status_fork_history_and_terminal_unmount`"),
    "src/sandbox.rs": ("A+C", "Sandbox create, list, delete, delete with logs through the host owner", "`SandboxApi::create`, `ManagedSandbox` stop/delete: S `engine_lifecycle.rs` (6), example `sandbox_lifecycle.rs`. `list` and log capture are outside the selected scope [D11]"),
    "src/workspace.rs": ("A+C", "Workspace mount, exec, commit, status, unmount routed through the host owner", "`WorkspaceApi` bind/attach/mount, commit, status, unmount, force_unmount: D `native_control.rs` (10), D `native_mount_routes.rs` (2). Managed Exec with its 30 s cap and status polling is dropped [D2]; ordinary execution is `SandboxApi::exec`"),
    "src/workspace_view.rs": ("O", "pin_view, view_lookup, view_list, view_read, view_readlink, view_status, release_view", VIEW),
}
SDK_TESTS = {
    "tests/agent_route.rs": {
        "sdk_only_lifecycle_edit_commit_readback_history_conflict_and_cleanup": ("A+C", "Managed Exec and HeadMoved conflict [D2] [D7]. Lifecycle: D `native_control.rs::native_mount_commit_status_fork_history_and_terminal_unmount`, D `mounted_commit.rs::r5_1_external_bash_changes_of_every_kind_are_committed_and_read_back_on_a_fresh_mount`"),
        "sdk_exec_reaches_inherited_descendant_beyond_4096_then_commits": ("A", "D `complete_installed_roots.rs::all_supported_native_paths_survive_install_with_full_oracles`, D `mounted_commit.rs::r5_1_...`"),
        "sdk_exec_moves_inherited_directory_and_commits_complete_tree": ("A", "W `captured_namespace_states.rs::a_moved_base_directory_has_no_row_and_no_value`, D `captured_commit.rs::every_kind_of_change_commits_through_the_driver_and_reads_back_from_a_fresh_bind`"),
        "sdk_exec_walks_270_components_and_checks_serials_after_commit": ("A", "W `captured_namespace.rs::a_deep_fresh_chain_ends_in_aliases_and_a_moved_base_directory`"),
    },
    "tests/exec_liveness_control.rs": {
        "silent_exec_exposes_native_progress_boundary": ("C", "[D2] (daemon Exec progress wire)"),
    },
    "tests/inherited_workspace.rs": {
        "pinned_directory_retains_forgotten_ancestors_and_detached_parent_refuses_mutation": ("A", "W `native_directory.rs::opened_directory_retains_parent_and_metadata_after_forget_and_rmdir`"),
        "base_directory_move_keeps_inherited_children_handles_and_commits": ("A", "W `captured_namespace_states.rs::a_moved_base_directory_has_no_row_and_no_value`, W `namespace.rs::rename_moves_replaces_and_refuses_cycles_without_descendant_rows`"),
        "moved_canonical_symlink_reads_target_by_serial": ("A", "W `nonfile.rs::linked_symlink_targets_follow_effective_layers_through_repeated_failed_captures`"),
        "moved_directory_keeps_frozen_g1_and_later_g2_write": ("A", "D `captured_commit.rs::mutations_after_the_capture_stay_out_of_its_root_and_survive_install`"),
        "growing_move_keeps_cached_descendant_reachable_beyond_4096_bytes": ("A", "W `captured_namespace.rs::a_deep_fresh_chain_ends_in_aliases_and_a_moved_base_directory`"),
        "growing_inherited_move_reaches_uncached_descendant_beyond_4096_bytes": ("A", "same"),
        "growing_rename_refuses_private_budget_before_publication": ("C", "[D3] [D8] (charged private budget)"),
        "a_successful_directory_rename_seals_once_and_refunds_exactly": ("C", "[D3] (budget refunds of the private index)"),
        "growing_prefix_move_has_descendant_independent_private_counts": ("A+C", "Private counts [D3]. W `namespace.rs::rename_moves_replaces_and_refuses_cycles_without_descendant_rows`, W `namespace_profile.rs::complete_operations_keep_point_work_as_names_and_inodes_grow`"),
        "fresh_upper_directory_move_is_the_control": ("A", "W `captured_namespace_states.rs::a_moved_fresh_directory_keeps_its_serial_and_children`"),
        "base_file_move_from_an_unmodified_root_keeps_its_identity": ("A", "W `captured_namespace.rs::renamed_and_moved_names_of_each_kind_keep_their_inodes`"),
        "phase_a_selected_origins_overlap_zero_hardlinks_and_completion_credit": ("O", VIEW + "; the non-view half (zero ranges, hard links) is W `captured_namespace_fragments.rs` and W `captured_namespace.rs`"),
        "phase_a_lease_admission_frozen_names_and_checked_release": ("O", VIEW),
        "phase_a_fresh_nonfile_removal_replacement_and_later_symlink_move": ("A", "W `captured_namespace_rebound.rs` (8 tests)"),
        "phase_a_exact_capability_refuses_before_dependent_inspection": ("C", "[D1] (Service grants)"),
        "phase_a_known_save_and_unknown_commit_keep_custody_without_replay": ("A", "D `mounted_commit_failures.rs::f3_unknown_history_outcome_keeps_custody_and_the_mount_still_serves`"),
        "phase_a_known_canonical_local_failure_resumes_same_selector_once": ("A", "D `mounted_commit_failures.rs::f4_known_publication_with_an_unattempted_install_keeps_custody`, D `store_commit.rs::known_publication_survives_an_unattempted_local_install`"),
        "phase_a_large_payload_append_resize_and_backward_base_copy": ("A", "W `captured_file_edits.rs::overlapping_writes_shrink_regrow_and_cross_cell_spans_match_final_bytes`"),
        "phase_a_namespace_cleanup_error_keeps_published_revision_and_identity": ("C", "[D3] (cleanup of the private page files)"),
    },
    "tests/init_project.rs": {
        "public_sdk_imports_fresh_100_and_1000_file_fixtures": ("A", "P `init_sqlite.rs::selected_profiles_init_100_and_1000_pass_the_full_namespace_oracle`, K `init.rs::init_seals_complete_root_and_first_branch_without_retained_handles`"),
        "host_setup_exposes_the_same_sdk_init": ("C", "[D1] (composed host Server)"),
        "source_refusals_duplicates_and_concurrent_bindings": ("A+C", "Server bindings [D1]. K `init.rs::refusal_preserves_existing_output_and_original_request`, P `acquisition_custody.rs::backing_inside_source_is_refused_before_an_operation_begins`"),
    },
    "tests/sandbox_log_capture.rs": {
        "diagnostic_logs_are_bounded_and_capture_failure_does_not_skip_cleanup": ("C", "[D11] (delete-time log capture is not in the selected SandboxApi scope)"),
    },
    "tests/support/phase_b_commit.rs": {
        "prepare_master": ("C", "Fixture preparation for the withdrawn host-mediated families [D1]"),
        "full_lowering_64mib": ("A+C", "Host lowering [D9]. D `product_commit_cost.rs::a_small_and_a_large_change_through_the_product_constructor_are_counted`"),
        "stage_headroom_2mib": ("C", "[D3] [D8] (private-disk headroom of staging)"),
        "commit_headroom_4mib": ("C", "[D3] [D8]"),
        "native_count_8192": ("A", "No edit-count cap: W `captured_file_edits.rs::many_edits_use_numbered_records_after_install_and_reads_survive_close`"),
        "native_count_10240": ("A", "same"),
    },
    "tests/support/phase_b_mutations.rs": {
        "mixed_live": ("A", "D `mounted_concurrency.rs::r6_1_twenty_four_processes_read_and_write_through_three_commits`"),
        "mixed_failures": ("A", "D `mounted_commit_failures.rs` (6 tests)"),
        "mixed_local_resume": ("A", "D `mounted_commit_failures.rs::f4_known_publication_with_an_unattempted_install_keeps_custody`"),
        "progress_custody": ("C", "[D2] (Exec progress custody)"),
        "many_commit_diagnostic": ("A", "D `mounted_cycles.rs::counts_plateau_over_twelve_cycles_with_maintenance_awaited_after_each_unmount`"),
    },
    "tests/support/phase_b_namespace.rs": {
        "move_scaling": ("A", "W `captured_namespace_cursor.rs::work_follows_the_change_and_not_the_installed_base`"),
        "deep_move_back": ("A", "W `captured_namespace_rebound.rs::a_base_directory_moved_away_and_back_keeps_its_stored_values_with_no_territory_walk`"),
        "retained_live_namespace": ("A", "D `mounted_install.rs::retained_descriptors_and_kernel_caches_are_unchanged_by_install`"),
    },
}
SDK_OTHER = {
    "Cargo.toml": ("C", "Depends on `../layerfs-api/core` (removed by F12) and `../layerfs-server`; cannot be loaded"),
    "examples/benchmark_init.rs": ("A", "`layerfs-project/examples/benchmark_init.rs`"),
    "examples/benchmark_shell.rs": ("C", "Driver of the withdrawn host-mediated shell-package family [D1] [D2]"),
}

# ---------------------------------------------------------------- daemon predecessor
DAEMON_SRC = {
    "src/lib.rs": ("A", "Declarations; exports `run`", "`layerfs-daemon/src/lib.rs`"),
    "src/main.rs": ("A", "Process entry", "`layerfs-daemon/src/bin/layerfs-daemon.rs`"),
    "src/config.rs": ("A+C", "Mount, control and writable-profile configuration from arguments", "`layerfs-daemon/src/application/config.rs`, `cli.rs`: D `native_application.rs::actual_daemon_install_hello_bind_status_no_constructor_and_session_end`, D `startup_cost.rs::admission_refusal_has_no_creation_receipt_or_artifact_effect`. Branch disk budget and Server endpoint are dropped [D12] [D1]"),
    "src/control.rs": ("A+C", "One authenticated control session: attach, mount, status, unmount, close", "`layerfs-daemon/src/control/` (operations, serve, registry): D `native_control.rs` (10). Separate close is withdrawn [D6]. Its dispatch of view operations is O-10"),
    "src/control_commit.rs": ("A+C", "Commit outcomes and writable observations on the control route", "`layerfs-daemon/src/control/operations.rs`, `store/commit.rs`: D `native_control.rs::product_control_commit_captures_the_frontier_releases_its_owners_and_is_then_up_to_date`, D `mounted_commit.rs` (7). Staged/composite split and HeadMoved [D7]"),
    "src/control_view.rs": ("O", "Authorized dispatch of the view-lease operations", VIEW),
    "src/execution.rs": ("C", "Bounded shell execution inside one mounted Workspace", "[D2]"),
    "src/headless.rs": ("C", "Stdin/stdout framed headless delivery", "[D9] (303/07 §4.1 names it for removal)"),
    "src/lifecycle.rs": ("A", "The one native owner shared by control and process shutdown", "`layerfs-daemon/src/application/owner.rs`, `control/registry.rs`: D `native_mount.rs::two_workspaces_share_one_dispatcher_and_unmount_independently`, D `cleanup_control.rs`"),
    "src/run.rs": ("A", "Process and connection assembly", "`layerfs-daemon/src/application/serve.rs`, `connection.rs`, `filesystem.rs`: D `native_application.rs`, D `observed_application.rs` (4)"),
    "src/transport.rs": ("C", "Reuse of the daemon-to-host Service transport", "[D1] [D9] (303/07 §4.1 names it for removal; the upstream pool that replaced it was itself retired by F12)"),
}
DAEMON_TESTS = {
    "tests/configuration.rs": {
        "mount_startup_rejects_invalid_inputs_before_connecting": ("A", "D `startup_cost.rs::admission_refusal_has_no_creation_receipt_or_artifact_effect`, D `e2_startup_receipts.rs::pre_creation_refusal_keeps_original_error_and_emits_unavailable_work`"),
        "control_configuration_is_explicit_separate_and_bounded": ("A", "B `daemon_records.rs::private_setup_is_exact_bounded_and_redacts_secret`"),
        "writable_profile_requires_branch_disk_budget_and_commit_control_endpoint": ("C", "[D12] [D13] (one mutable profile; no branch disk budget)"),
    },
}
DAEMON_OTHER = {
    "Cargo.toml": ("C", "Depends on the active `layerfs-fuse` and `layerfs-workspace`, whose API it does not match; cannot be loaded"),
    "Dockerfile": ("C", "Image of the old daemon. Current images are built by the Sandbox lifecycle and the harness"),
    "examples/transport_probe.rs": ("C", "Probe of the daemon-to-host transport [D1]"),
    "tests/control_attach.py": ("A", "Docker driver. D `native_mount.rs`, D `native_mount_routes.rs`"),
    "tests/control_attach_startup.py": ("A", "Docker driver. D `native_mount.rs::attach_refusals_have_no_effect_and_a_failed_attach_returns_to_unattached`"),
    "tests/control_close.py": ("C", "Separate close [D6]"),
    "tests/control_commit.py": ("A+C", "Docker driver. D `mounted_commit.rs`, D `mounted_commit_failures.rs`; HeadMoved rows [D7]"),
    "tests/control_commit_wire.py": ("A", "Wire helper. B `control_golden.rs`"),
    "tests/control_mount.py": ("A", "Docker driver. D `native_control.rs`"),
    "tests/control_status.py": ("A", "Docker driver. D `native_control.rs::status_retains_known_publication_when_the_engine_is_unavailable`, B `control_golden.rs::status_keeps_its_bytes_at_every_activity_and_native_phase`"),
    "tests/control_unmount.py": ("A", "Docker driver. D `mounted_drain.rs`, D `native_custody.rs`, D `forced_unmount.rs`"),
    "tests/docker_faults.py": ("A+C", "Docker fault driver over the host transport [D1]. Channel faults: B `native.rs`"),
    "tests/docker_route.py": ("C", "Headless host route [D1]"),
    "tests/history_route.py": ("A+C", "History over the host route [D1]. D `native_control.rs::native_mount_commit_status_fork_history_and_terminal_unmount`"),
    "tests/metadata_route.py": ("C", "Service metadata constructor route [D1] [D9]"),
    "tests/mount_startup.py": ("A", "Docker driver. D `native_mount.rs::ready_mount_serves_the_complete_root_to_unregistered_access_then_drains`"),
    "tests/mounted_read.py": ("A", "Docker driver. D `native_mount.rs`, D `read_cost.rs`"),
    "tests/transport_diagnostic.py": ("C", "Driver of `transport_probe` [D1]"),
}

# ---------------------------------------------------------------- Bridge predecessor
BRIDGE_SRC = {
    "src/lib.rs": ("A", "Declarations", "`layerfs-bridge/src/lib.rs`"),
    "src/adapters/mod.rs": ("A", "Declarations", "—"),
    "src/adapters/native/mod.rs": ("A", "Declarations of the native adapter", "`layerfs-bridge/src/native/`"),
    "src/adapters/native/client.rs": ("A+C", "One logical operation at a time with concurrent upload and response", "Logical data operations [D1] [D9]. Control calls: SDK `control/connection.rs` (K `observed_control.rs`); its view calls are O-10"),
    "src/adapters/native/connection.rs": ("A+C", "Authenticated duplex connection, bounded records, absolute deadlines", "`layerfs-bridge/src/native/`: B `native.rs` (9 tests). Deadlines and the timeout retry loop are not carried [D5]"),
    "src/adapters/native/payload.rs": ("C", "Exact-length logical stream adapters", "[D9]"),
    "src/adapters/native/pipe.rs": ("C", "Deadline-aware pipe I/O with cancellation", "[D5] [D9] (headless pipe delivery)"),
    "src/adapters/native/protocol/mod.rs": ("C", "Declarations", "—"),
    "src/adapters/native/protocol/control.rs": ("A", "Daemon control payloads", "`layerfs-bridge/src/control/`: B `control_records.rs` (3), B `control_golden.rs` (5)"),
    "src/adapters/native/protocol/execution.rs": ("C", "Exec wire payload", "[D2]"),
    "src/adapters/native/protocol/frame.rs": ("A+C", "Fixed-width local frames", "Logical framing retired by F12 [D9]. Native records: B `native.rs::malformed_record_quarantines_both_directions_before_body_allocation`"),
    "src/adapters/native/protocol/history_failure.rs": ("C", "History failure context on the wire", "[D1] (history no longer crosses the Bridge as a data call; fork/history are control verbs)"),
    "src/adapters/native/protocol/metadata.rs": ("A+C", "Checked binary metadata of every logical operation", "[D9] (303/07 §4.1 names it for removal). Its view-request encodings are O-10"),
    "src/adapters/native/protocol/prepared.rs": ("C", "Prepared request header", "[D9]"),
    "src/adapters/native/protocol/response.rs": ("A+C", "Closed terminal result encoding", "[D9]. Control replies: B `control_records.rs::replies_preserve_scoped_status_conflict_and_known_publication`. Its view results are O-10"),
    "src/adapters/native/protocol/state.rs": ("C", "Input grammar and cumulative work of logical streams", "[D9]"),
    "src/adapters/native/protocol/workspace_commit.rs": ("A+C", "Commit terminals and writable Status encodings", "B `control_golden.rs::binding_commit_history_and_session_replies_keep_their_bytes`; staged/HeadMoved encodings [D7]"),
    "src/adapters/native/protocol/workspace_view.rs": ("O", "View-lease terminal results", VIEW),
    "src/adapters/native/server.rs": ("C", "Supplied-handler logical server", "[D1] [D9]"),
    "src/contract/mod.rs": ("C", "Declarations", "—"),
    "src/contract/caller.rs": ("A", "Authentication evidence of a caller", "`layerfs-bridge/src/native/` verified peer: B `native.rs::wrong_static_identity_fails_the_actual_handshake`"),
    "src/contract/control.rs": ("A", "Daemon-targeted control requests", "`layerfs-bridge/src/control/`: B `control_records.rs::commands_are_bounded_exact_and_reject_every_truncated_prefix`"),
    "src/contract/execution.rs": ("C", "Bounded daemon Exec request and result", "[D2]"),
    "src/contract/history.rs": ("A+C", "History query/command surface and typed results", "Wire surface [D1]. Semantics: PE `history_*.rs`; control verbs: B `control_golden.rs::binding_commit_history_and_session_replies_keep_their_bytes`"),
    "src/contract/metadata.rs": ("C", "Portable metadata construction requests", "[D9]"),
    "src/contract/outcome.rs": ("A+C", "Typed product outcomes separate from transport uncertainty", "SDK `operation.rs` (`OperationCause`, `OperationFailure`): D `native_control.rs::original_lost_control_reply_is_not_replayed_or_settled_by_an_observer`. Its view outcomes are O-10"),
    "src/contract/prepared_stream.rs": ("C", "Prepared namespace as an ordered stream", "[D9] (303/07 §4.1)"),
    "src/contract/request.rs": ("A+C", "Closed operation profile, budgets and the 4 GiB file constant", "[D9] [D8]. Control profile: B `control_records.rs`. Its view operations are O-10"),
    "src/contract/source.rs": ("C", "Cooperative logical input capability", "[D9] (303/07 §4.1)"),
    "src/contract/workspace_commit.rs": ("A+C", "Commit report and writable observations", "B `control_records.rs::replies_preserve_scoped_status_conflict_and_known_publication`; stage records [D7]"),
    "src/contract/workspace_request.rs": ("A+C", "Admission checks of the control request family", "B `control_records.rs::native_block_is_additive_and_bounded_fields_are_refused_before_send`. Its view requests are O-10"),
    "src/contract/workspace_view.rs": ("O", "View-lease requests and results", VIEW),
}
_B_NATIVE = "B `native.rs::authenticated_duplex_records_stream_beyond_one_window_with_fixed_buffers`"
BRIDGE_TESTS = {
    "tests/aead_profile.rs": {"negotiated_suite_matches_the_compiled_backend": ("A", "B `native.rs::successful_native_channels_enable_nodelay_on_both_authenticated_sockets` (the channel refuses a build without the required AEAD profile)")},
    "tests/agent_control.rs": {"selected_mount_exec_and_identity_round_trip": ("A+C", "Exec half [D2]. B `control_records.rs::commands_are_bounded_exact_and_reject_every_truncated_prefix`")},
    "tests/attributes.rs": {
        "complete_attributes_roundtrip_and_reject_invalid_fields": ("A+C", "Wire [D9]. F `attributes.rs::attributes_preserve_signed_fraction_identity_mode_and_link_count`"),
        "identity_inspect_queries_roundtrip_and_check_bounds": ("C", "[D9] (inspect queries of the Service)"),
    },
    "tests/construct_metadata.rs": {k: ("C", "[D9] (metadata constructor wire)") for k in (
        "constructor_has_exact_wire_shapes_body_limits_and_shared_metadata_grant",
        "constructor_refuses_invalid_portable_fields_profiles_and_response_bodies",
        "native_constructor_correlates_every_echo_and_preserves_unknown_without_replay")},
    "tests/construct_symlink.rs": {k: ("C", "[D9] (symlink constructor wire)") for k in (
        "constructor_has_exact_bounds_opaque_target_and_shared_content_grant",
        "constructor_rejects_malformed_metadata_and_nonzero_result_body_budget",
        "native_constructor_correlates_saved_length_and_keeps_terminal_loss_unknown_without_replay")},
    "tests/early_refusal.rs": {"early_failure_is_delivered_while_the_bounded_upload_closes": ("C", "[D9] (logical upload)")},
    "tests/file_save_v2.rs": {"authenticated_capability_and_v1_v2_metadata_are_distinct": ("C", "[D9]")},
    "tests/history_delivery.rs": {"mutation_result_data_is_rejected_before_any_output": ("C", "[D1] [D9]")},
    "tests/history_protocol.rs": {k: ("C", "[D1] [D9] (history wire protocol). Semantics: PE `history_*.rs`") for k in (
        "every_query_and_command_round_trips", "native_import_declares_progress_response_budget",
        "a_prepared_declaration_is_the_exact_body_it_describes", "a_prepared_update_wider_than_one_metadata_frame_round_trips",
        "profile_and_opcode_must_agree", "unknown_suboperations_are_refused_before_mutation",
        "identity_widths_and_tags_are_checked", "page_and_count_bounds_are_checked",
        "the_retired_pathless_init_tag_is_refused_and_unassigned", "every_reply_round_trips",
        "a_reply_tag_outside_the_closed_union_is_refused", "failure_codes_round_trip_and_stay_typed",
        "permission_bits_are_total_and_legacy_mask_grants_nothing", "classification_is_exhaustive_and_semantic",
        "minimum_and_maximum_record_encodings_match_the_frozen_widths", "history_page_budget_includes_tags_counts_and_continuation",
        "history_failure_context_round_trips_without_changing_legacy_frames", "invalid_terminal_reservation_and_descriptor_serial_are_refused",
        "the_retired_init_and_the_prepared_commands_are_the_only_replaced_encodings")},
    "tests/native_connections.rs": {
        "exec_progress_is_authenticated_and_has_no_result_bytes": ("C", "[D2]"),
        "caller_deadline_covers_connect_and_hello": ("C", "[D5]"),
        "repeated_native_connections_authenticate_with_ordinary_tcp": ("A", "B `native.rs::successful_native_channels_enable_nodelay_on_both_authenticated_sockets`"),
        "definite_missing_inspect_keeps_one_authenticated_session": ("A+C", "Inspect [D9]. D `native_control.rs::control_busy_keeps_the_channel_healthy_for_a_later_explicit_call`"),
        "productive_upload_keeps_the_response_wait_alive": ("C", "[D5] [D9]"),
        "missing_native_reply_preserves_read_deadline_but_not_save_custody": ("A+C", "Deadline [D5]. B `native.rs::terminal_reply_retains_eof_and_original_platform_fence_outcome`, D `native_control.rs::original_lost_control_reply_is_not_replayed_or_settled_by_an_observer`"),
    },
    "tests/pipe_cancel.rs": {"cancelled_read_exact_terminates": ("C", "[D9] (headless pipe)"), "cancelled_write_all_terminates": ("C", "[D9]")},
    "tests/pipe_deadline.rs": {"a_full_pipe_fails_at_the_deadline_instead_of_blocking": ("C", "[D5] [D9]")},
    "tests/portable_metadata.rs": {k: ("C", "[D9] (metadata operation wire)") for k in (
        "metadata_operation_has_exact_shapes_and_an_independent_store_grant",
        "invalid_portable_fields_and_profiles_are_refused_before_delivery",
        "native_metadata_reply_must_echo_the_exact_input_and_preserve_unknown_delivery")},
    "tests/prepared_stream.rs": {k: ("C", "[D9] (303/07 §4.1 prepared stream)") for k in (
        "a_declared_stream_round_trips_row_for_row", "an_io_error_at_the_trailing_byte_check_is_not_eof",
        "a_stream_that_lies_about_its_rows_is_refused", "a_stream_whose_rows_are_out_of_order_is_refused",
        "a_declaration_past_the_charged_bound_is_refused")},
    "tests/protocol.rs": {
        "fixed_framing_rejects_lengths_states_and_truncations": ("A+C", "[D9]. B `native.rs::malformed_record_quarantines_both_directions_before_body_allocation`"),
        "all_operation_metadata_roundtrips_and_caps_are_checked": ("C", "[D9]"),
        "final_file_stream_charges_extent_records_separately_from_file_length": ("C", "[D9]"),
        "terminal_types_and_explicit_continuation_roundtrip": ("C", "[D9]"),
        "remote_budget_only_shortens_the_declared_duration": ("C", "[D5]"),
        "declared_large_input_has_a_size_consistent_frame_and_time_budget": ("C", "[D5] [D9]"),
    },
    "tests/relay_write.rs": {"result_frames_reach_the_consumer_one_write_each": ("C", "[D9]")},
    "tests/source.rs": {"portable_source_handles_dynamic_input_deadline_and_cancellation": ("C", "[D5] [D9]")},
    "tests/stream_fragmentation.rs": {
        "short_source_reads_form_bounded_body_frames": ("A+C", "[D9]. " + _B_NATIVE),
        "short_logical_writes_form_bounded_result_frames": ("A+C", "[D9]. " + _B_NATIVE),
        "handler_failure_discards_pending_tail_without_drop_flush": ("C", "[D9]"),
        "buffered_output_checks_deadline_before_accepting_another_fragment": ("C", "[D5]"),
    },
    "tests/upload_batch.rs": {"bulk_upload_batches_records_without_changing_frames": ("C", "[D9]")},
    "tests/workspace_attach.rs": {
        "attach_is_identity_only_bounded_profile_three_mutation": ("A", "B `control_records.rs::commands_are_bounded_exact_and_reject_every_truncated_prefix`"),
        "attach_and_failed_status_preserve_codes_without_widening_lifecycle": ("A", "B `control_golden.rs::every_refusal_code_keeps_its_bytes`"),
        "authenticated_attach_and_status_correlate_without_replay": ("A", "D `native_mount_routes.rs::lost_bind_and_attach_acknowledgements_are_located_without_replay`"),
    },
    "tests/workspace_close_clean.rs": {
        "lifecycle_bounds_and_shared_outcomes_preserve_distinct_wire_bytes": ("A+C", "Separate close [D6]. B `control_golden.rs::every_request_tag_keeps_its_bytes`"),
        "authenticated_lifecycle_correlates_each_variant_and_identity_without_replay": ("A+C", "[D6]. D `native_control.rs::original_lost_control_reply_is_not_replayed_or_settled_by_an_observer`"),
    },
    "tests/workspace_commit.rs": {
        "commit_request_has_its_own_budget_and_never_store_authority": ("A+C", "Time budget [D5]. B `control_records.rs::commands_are_bounded_exact_and_reject_every_truncated_prefix`"),
        "commit_terminal_preserves_full_known_and_observed_records_with_bounded_bytes": ("A", "B `control_records.rs::replies_preserve_scoped_status_conflict_and_known_publication`"),
        "writable_status_preserves_submission_and_reachable_partial_commit_state": ("A", "B `control_golden.rs::status_keeps_its_bytes_at_every_activity_and_native_phase`"),
        "authenticated_commit_and_writable_status_correlate_and_never_replay": ("A", "D `native_control.rs::another_control_channel_observes_running_commit_and_refuses_unmount_before_effect`"),
    },
    "tests/workspace_status.rs": {
        "status_profile_is_bounded_and_has_no_store_permission": ("A", "B `control_records.rs::commands_are_bounded_exact_and_reject_every_truncated_prefix`"),
        "status_reply_preserves_exact_identity_and_refuses_bad_flags_or_closed_counts": ("A", "B `control_golden.rs::status_keeps_its_bytes_at_every_activity_and_native_phase`"),
        "authenticated_status_rejects_mismatched_identity_and_result_data_without_unknown_mutation": ("A", "K `observed_control.rs::observed_reply_keeps_original_exact_token_validation`"),
    },
    "tests/workspace_unmount.rs": {
        "unmount_is_an_exact_bounded_lifecycle_mutation_without_store_grants": ("A", "B `control_golden.rs::every_request_tag_keeps_its_bytes`"),
        "entered_outcomes_have_exact_identity_bounds_and_a_closed_retained_code_set": ("A", "B `control_golden.rs::ready_located_and_retained_keep_their_bytes`, B `forced_records.rs` (5)"),
        "authenticated_entered_attempts_and_pre_admission_failures_remain_distinct": ("A", "D `native_custody.rs::an_unmount_that_cannot_revoke_stops_retained_and_later_replies_repeat_it`"),
        "delivered_bad_or_lost_unmount_results_are_unknown_and_never_replayed": ("A", "D `native_control.rs::original_lost_control_reply_is_not_replayed_or_settled_by_an_observer`"),
    },
    "tests/workspace_view.rs": {
        "view_requests_round_trip_and_refuse_malformed_tokens_and_names": ("O", VIEW),
        "view_results_round_trip_the_native_codec": ("O", VIEW),
    },
}
BRIDGE_OTHER = {
    "Cargo.toml": ("C", "Uses workspace inheritance while excluded; cannot be loaded"),
    "examples/fault_peer.rs": ("A", "Fault peer of the channel tests. B `native.rs` builds its own peers"),
    "examples/public_key.rs": ("A", "Key derivation helper. Daemon private setup: B `daemon_records.rs`"),
    "examples/socket_bounds.rs": ("A", "Socket buffer observation. B `native.rs::authenticated_duplex_records_stream_beyond_one_window_with_fixed_buffers`"),
    "tests/fragmented_saved_root.py": ("C", "Docker driver of the host Save route [D1]"),
    "tests/support/": ("C", "Helpers of the tests above"),
    "tests/fixtures/history-wire-a4a144af.hex": ("C", "Frozen bytes of the retired history wire [D1] [D9]"),
}

# ---------------------------------------------------------------- Workspace predecessor
# Source is classified by directory with per-file overrides.
WS_DIR = {
    "src/backing/": ("C", "Private page files, the binary B+ tree, generation packs, charged budgets, ownership ledger and reclamation of the private backing", "[D3]: deleted outright (13,866 lines per 303/07 §4.3). State lives in the daemon's SQLite overlay: O `engine.rs` (12), O `payload.rs` (4), O `orphans.rs` (11), O `lifetimes.rs` (3), O `reclaim_cost.rs` (3)"),
    "src/commit/": ("A+C", "Capture lowering, host upload of final file sequences, prepared-stream construction, staged and composite Commit, local reconciliation", "Host-side construction and upload [D1] [D9]; staged/composite split and HeadMoved [D7]. Commit in the daemon: W `captured_namespace*.rs` (76 tests), W `captured_file_edits.rs` (14), D `store_commit.rs` (8), D `product_commit.rs` (11), D `mounted_commit.rs` (7), D `mounted_commit_failures.rs` (6), D `mounted_install.rs` (5)"),
    "src/filesystem/": ("A+C", "Filesystem semantics over the private active index: create, mkdir, mknod, link, symlink, unlink, rmdir, rename, open, read, write, resize, attributes, directory listing", "Behaviour kept and rewritten (303/07 §4.1) over the overlay: W `namespace.rs` (5), W `namespace_view.rs` (5), W `payload.rs` (4), W `native_visit.rs` (6), W `native_directory.rs` (4), W `nonfile.rs` (3), D `native_mutation.rs` (2), D `native_coherence.rs` (6). The active-index mechanism is [D3]"),
    "src/overlay/": ("A+C", "Generation-local directory deltas, extent pieces and the private capture", "Mechanism [D3]. O `captured_namespace.rs` (5), O `captured_runs.rs` (6), O `frontier.rs` (3), O `payload_runs.rs` (4)"),
    "src/runtime/": ("A+C", "Workspace state, node table, attachment custody, projection coherence, host calls and lifecycle", "Kept and rewritten (303/07 §4.1): `layerfs-workspace/src/` plans plus `layerfs-daemon` owner and registry; D `owner.rs` (12), D `native_mount.rs` (3), D `mounted_drain.rs` (5). Per-mutation kernel notification [D4], blocking reply permits and deadlines [D5], calls to the host Server [D1]"),
}
WS_FILE = {
    "src/lib.rs": ("A+C", "Exports, including the page-store test seam and view-lease types", "`layerfs-workspace/src/lib.rs`. The `sequence` seam belongs to the private backing [D3]; the view exports are O-10"),
    "src/types.rs": ("A+C", "Portable request and result types, limits (128 handles, 8 MiB budget, 4 GiB file)", "`layerfs-workspace/src/` types. The fixed limits are retirement targets [D8]"),
    "src/commit_types.rs": ("A+C", "Staged and composite Commit outcomes", "Bridge `control` replies and SDK `OperationFailure`. Staged/composite split [D7]"),
    "src/runtime/view_leases.rs": ("O", "Charged registry of held public read-only view leases (32 views)", VIEW),
    "src/filesystem/view_reads.rs": ("O", "Public read-only view leases over one pinned selected view", VIEW),
    "src/filesystem/active_view.rs": ("O", "Name resolution and bounded listing against one pinned active revision", VIEW + ". Ordinary listing is W `namespace_view.rs`"),
    "src/filesystem/namespace_view.rs": ("A+C", "View-bound namespace resolution for mounted lookups", "W `namespace_view.rs` (5 tests); the lease-bound entry points are O-10"),
    "src/runtime/coherence.rs": ("A+C", "Projection binding, bounded reply exclusion, checked mutation completion and notification", "`layerfs-fuse/src/coherence/`: D `native_coherence.rs` (6). Notification and the reply gate [D4] [D5]"),
    "src/runtime/host.rs": ("C", "Calls to the host Server for Save, construction and history", "[D1]. Its view-lease host calls are O-10"),
    "src/runtime/attachment.rs": ("A", "Failed attachment custody and explicit cleanup", "D `native_mount.rs::attach_refusals_have_no_effect_and_a_failed_attach_returns_to_unattached`, D `cleanup_control.rs`"),
    "src/commit/upload.rs": ("C", "Fixed-window upload of the captured file sequence to the host", "[D1] [D9]"),
    "src/commit/stream.rs": ("C", "Prepared update as a replayable stream of rows", "[D9]"),
    "src/commit/source.rs": ("C", "Bridge Source over captured replacement spans", "[D9]"),
    "src/filesystem/projection_counters.rs": ("A", "Per-operation counts of callbacks and upstream calls", "`layerfs-fuse/src/request/accounting.rs`; D `read_cost.rs`, D `directory_cost.rs`"),
}

def _all(names, cls, where):
    return {n: (cls, where) for n in names.split()}

WS_TESTS = {
    "tests/attachment.rs": {
        "exact_attachment_observation_preserves_the_existing_owner": ("A", "D `native_mount_routes.rs::lost_bind_and_attach_acknowledgements_are_located_without_replay`"),
        "active_attachment_is_observable_and_refuses_cleanup_without_holding_registry": ("A", "D `cleanup_control.rs::explicit_cleanup_observes_after_registry_removal_without_recreating_a_binding`"),
        "unacquired_failure_and_expired_admission_leave_no_attachment": ("A+C", "Deadline [D5]. D `native_mount.rs::attach_refusals_have_no_effect_and_a_failed_attach_returns_to_unattached`"),
        "attachment_retained": ("A", "D `native_custody.rs::an_unmount_that_cannot_revoke_stops_retained_and_later_replies_repeat_it`"),
        "attachment_substitution": ("A", "D `mounted_cycles.rs::simultaneous_mounts_over_related_roots_are_isolated_and_a_stale_token_never_redirects`"),
        "attachment_concurrent_cleanup": ("A", "D `cleanup_control.rs`"),
        "attachment_cleanup_deadline": ("C", "[D5]"),
        "attachment_branch_capacity": ("C", "[D12]"),
        "attachment_mount_substitution": ("A", "D `mounted_cycles.rs::simultaneous_mounts_over_related_roots_are_isolated_and_a_stale_token_never_redirects`"),
    },
    "tests/backing_ownership.rs": _all(
        "routine_reclamation_does_not_rescan_earlier_acquisitions released_inputs_are_reclaimed_by_the_next_write simultaneous_last_owner_drops_leave_one_release_candidate a_failed_release_preserves_later_release_candidates refused_admission_preserves_its_existing_owners reader_and_owner_pins_survive_routine_maintenance",
        "A+C", "Private ownership ledger [D3]; write-triggered reclamation is withdrawn (303/08 K18). Overlay reclamation: O `reclaim_cost.rs` (3), O `lifetimes.rs` (3), D `owner.rs::last_release_starts_automatic_cleanup_during_idle_and_unrelated_live_work`"),
    "tests/coherence.rs": {
        "coherence_visibility": ("A", "D `native_mutation.rs::namespace_mutations_are_visible_at_once_and_refusals_stay_refused`"),
        "coherence_read_race": ("A+C", "Reply gate [D5]. D `mounted_concurrency.rs::readers_on_two_workspaces_read_exact_bytes_while_one_is_written`"),
        "coherence_exec": ("B", "Execution of a program stored in the Workspace. **Migrated**: D `mounted_execute.rs::a_stored_program_executes_and_its_in_place_rewrite_executes_next` (added in this stage; Linux receipt `execute-attempt1-linux-mounted_execute.txt`)"),
        "coherence_native_save": ("A", "D `mounted_install.rs::retained_descriptors_and_kernel_caches_are_unchanged_by_install`"),
        "coherence_completion": ("C", "[D4] (notification completion)"),
        "coherence_deadline": ("C", "[D5]"),
        "coherence_notify_failure": ("C", "[D4]"),
        "coherence_truncate_failure": ("A+C", "[D4]. D `native_coherence.rs::size_never_shrinks_under_concurrent_append_and_refusals_stay_refused`"),
    },
    "tests/commit_overlap.rs": _all(
        "a_frozen_walk_page_read_is_held_with_the_writer_gate_free a_namespace_lowering_page_read_is_held_with_the_writer_gate_free a_page_read_under_the_writer_gate_reports_the_held_gate",
        "A+C", "Writer gate of the private index [D3]. D `store_commit.rs::a_held_producer_does_not_hold_workspace_metadata_or_read_capacity`, W `captured_namespace_order.rs` (2)"),
    "tests/commit_progress.rs": {"a_frozen_transfer_admits_a_mounted_mutation_between_its_frames": ("A", "D `mounted_install.rs::writes_during_a_commit_stay_live_and_reach_the_next_commit`")},
    "tests/commit_staged.rs": {
        "commit_repeated": ("A", "D `mounted_commit.rs::r5_8_five_incremental_commits_on_one_mount_each_read_back_completely`"),
        "commit_successor": ("A", "D `store_commit.rs::later_mutation_survives_capture_publication_and_known_install`"),
        "commit_mounted_successor": ("A", "D `mounted_install.rs::writes_during_a_commit_stay_live_and_reach_the_next_commit`"),
        "commit_mounted_build_overlap": ("A", "D `mounted_concurrency.rs::r6_2_a_commit_against_twenty_writers_holds_an_exact_prefix_of_each`"),
        "commit_selectors": ("C", "[D7] (stage selectors)"),
        "commit_denied": ("C", "[D1] (Service denial)"),
        "commit_lost_result": ("A", "D `mounted_commit_failures.rs::f3_unknown_history_outcome_keeps_custody_and_the_mount_still_serves`"),
        "commit_reconcile_failure": ("A", "D `mounted_commit_failures.rs::f4_known_publication_with_an_unattempted_install_keeps_custody`"),
        "commit_consumed_stage": ("C", "[D7]"),
        "commit_head_moved": ("C", "[D7]. Replacement: D `product_commit.rs::a_stale_unchanged_candidate_overwrites_a_moved_head`"),
        "commit_cycles": ("A", "D `mounted_cycles.rs::counts_plateau_over_twelve_cycles_with_maintenance_awaited_after_each_unmount`"),
        "commit_headroom": ("C", "[D3] [D12]"),
        "commit_frontier": ("A", "D `mounted_commit.rs::r5_3_commit_captures_what_every_launch_published_whatever_became_of_the_process`"),
        "commit_remote_admission": ("A+C", "Service admission [D1]. D `mounted_commit_failures.rs::f1_store_busy_before_save_is_settled_and_a_later_commit_is_exact`"),
    },
    "tests/composite.rs": {
        "composite_progress_custody": ("C", "[D2] [D9] (progress frames of the host command)"),
        "composite_clean": ("A", "D `product_commit.rs::an_unchanged_workspace_is_up_to_date_and_creates_no_commit`"),
        "composite_clean_successor": ("A", "D `mounted_commit.rs::r5_2_unchanged_is_up_to_date_and_a_change_is_committed_once`"),
        "composite_repeated": ("A", "D `product_commit.rs::repeated_incremental_commits_keep_the_store_open_and_each_root_is_exact`"),
        "composite_successor": ("A", "D `store_commit.rs::later_mutation_survives_capture_publication_and_known_install`"),
        "composite_native_save": ("A", "D `product_commit.rs::every_kind_of_change_commits_through_the_product_constructor`"),
        "composite_unknown_save": ("A", "D `store_commit.rs::nested_storage_unknown_keeps_original_capture_and_blocks_another_commit`"),
        "composite_lost_result": ("A", "D `product_commit.rs::an_unknown_history_outcome_keeps_the_reader_and_owner_with_the_failure`"),
        "composite_reconcile_failure": ("A", "D `store_commit.rs::known_publication_survives_an_unattempted_local_install`"),
        "composite_denied": ("C", "[D1]"),
        "composite_head_moved": ("C", "[D7]"),
        "composite_refusals": ("A", "D `product_commit.rs::the_product_constructor_classifies_and_settles_a_definite_refusal`"),
        "composite_metadata_only": ("A", "W `captured_namespace_states.rs::a_base_file_with_only_metadata_changes_keeps_its_content_root`"),
        "composite_frontier": ("A", "D `native_control.rs::product_control_commit_captures_the_frontier_releases_its_owners_and_is_then_up_to_date`"),
        "composite_remote_admission": ("A+C", "[D1]. D `product_commit.rs::a_commit_waits_for_owner_admission_and_is_not_refused`"),
    },
    "tests/create.rs": {
        "create_semantics": ("A", "W `namespace.rs::create_mkdir_symlink_and_link_publish_parent_and_reference_effects_atomically`"),
        "create_flags_permissions": ("A", "D `native_mutation.rs::namespace_mutations_are_visible_at_once_and_refusals_stay_refused`"),
        "create_successor": ("A", "D `captured_commit.rs::mutations_after_the_capture_stay_out_of_its_root_and_survive_install`"),
        "create_capacity": ("C", "[D3] [D8] (charged identity budget)"),
        "create_refusals": ("A", "W `namespace.rs::unrepresentable_names_targets_and_reservations_are_refused_before_any_job`"),
        "create_reserve_denied": ("A+C", "Service denial [D1]. D `mounted_failure_scope.rs::a_create_with_no_serial_range_under_a_held_store_writer_is_eagain_with_no_effect`"),
        "create_reserve_unknown": ("A+C", "[D1]. same"),
    },
    "tests/fresh_stream.rs": {
        "fresh_stream_mounted_dsh": ("A", "W `captured_namespace_states.rs::a_fresh_file_is_constructed_from_its_captured_runs`"),
        "fresh_stream_captured_replay": ("A+C", "Replay bound of the host upload [D9]. W `captured_file_edits.rs::length_growth_and_true_new_file_do_not_use_a_fabricated_base`"),
    },
    "tests/keyed_tree.rs": {"one_walk_reaches_each_leaf_once_and_one_delete_rewrites_one_path": ("C", "[D3] (private keyed B+ tree)")},
    "tests/maintenance.rs": _all(
        "maintenance_payload_churn maintenance_mutation_churn maintenance_cross_workspace maintenance_frozen maintenance_payload_failure maintenance_metadata_failure",
        "A+C", "Private-backing maintenance [D3]. D `mounted_cycles.rs::counts_plateau_over_twelve_cycles_beside_a_running_sibling_writer`, D `owner.rs::idle_cleanup_runs_without_an_explicit_reclaim_or_status_job`, O `cleanup_observation.rs` (2)"),
    "tests/mkdir.rs": {
        "mkdir_semantics": ("A", "W `namespace.rs::create_mkdir_symlink_and_link_publish_parent_and_reference_effects_atomically`"),
        "mkdir_successor": ("A", "W `captured_namespace.rs::mutations_after_the_capture_are_absent_from_its_root_and_present_in_the_next`"),
        "mkdir_capacity": ("C", "[D3] [D8]"),
        "mkdir_refusals": ("A", "W `namespace.rs::unrepresentable_names_targets_and_reservations_are_refused_before_any_job`"),
        "mkdir_reserve_denied": ("A+C", "[D1]. D `mounted_failure_scope.rs::a_create_with_no_serial_range_under_a_held_store_writer_is_eagain_with_no_effect`"),
        "mkdir_reserve_unknown": ("A+C", "[D1]. same"),
    },
    "tests/mounted_create.rs": {
        "mounted_create_kernel": ("A", "D `native_mutation.rs::write_append_and_truncate_are_exact_in_cache_and_daemon`"),
        "mounted_create_existing": ("A", "D `native_mutation.rs::namespace_mutations_are_visible_at_once_and_refusals_stay_refused` (EEXIST)"),
        "mounted_create_visibility": ("A", "D `native_coherence.rs::a_lookup_racing_create_unlink_and_rename_never_binds_a_stale_inode`"),
        "mounted_create_permit": ("C", "[D5] (reply permit)"),
        "mounted_create_notification_failure": ("C", "[D4]"),
        "mounted_create_successor": ("A", "D `mounted_install.rs::writes_during_a_commit_stay_live_and_reach_the_next_commit`"),
    },
    "tests/mounted_mkdir.rs": {
        "mounted_mkdir_kernel": ("A", "D `native_mutation.rs::namespace_mutations_are_visible_at_once_and_refusals_stay_refused`"),
        "mounted_mkdir_visibility": ("A", "same"),
        "mounted_mkdir_permit": ("C", "[D5]"),
        "mounted_mkdir_notification_failure": ("C", "[D4]"),
    },
    "tests/mounted_namespace.rs": {
        "mounted_namespace_kernel": ("A", "D `native_mutation.rs::namespace_mutations_are_visible_at_once_and_refusals_stay_refused`, D `mounted_links.rs`"),
        "mounted_namespace_durability": ("A", "D `mounted_commit.rs::r5_1_external_bash_changes_of_every_kind_are_committed_and_read_back_on_a_fresh_mount`"),
    },
    "tests/mounted_symlink.rs": {
        "mounted_symlink_kernel": ("A", "D `native_mutation.rs::namespace_mutations_are_visible_at_once_and_refusals_stay_refused`, D `read_cost.rs::read_open_and_readlink_cost_exactly_this_at_any_size_and_beside_unrelated_rows`"),
        "mounted_symlink_visibility_successor": ("A", "D `mounted_commit.rs::r5_1_...`"),
        "mounted_symlink_permit": ("C", "[D5]"),
        "mounted_symlink_notification_failure": ("C", "[D4]"),
    },
    "tests/namespace.rs": {
        "namespace_setattr": ("A", "W `namespace.rs::chmod_and_utimens_follow_the_portable_grammar_and_keep_one_mtime`"),
        "namespace_mknod": ("A", "W `namespace.rs::create_mkdir_symlink_and_link_publish_parent_and_reference_effects_atomically`"),
        "namespace_link": ("A", "same; W `directory_links.rs` (5)"),
        "namespace_unlink": ("A", "W `namespace.rs::unlink_and_rmdir_remove_one_reference_and_keep_directory_counts_exact`"),
        "namespace_unlink_fresh": ("A", "W `captured_namespace_states.rs::inodes_created_and_removed_inside_the_capture_are_never_constructed`"),
        "namespace_rmdir": ("A", "W `namespace.rs::unlink_and_rmdir_remove_one_reference_and_keep_directory_counts_exact`"),
        "namespace_rename": ("A", "W `namespace.rs::rename_moves_replaces_and_refuses_cycles_without_descendant_rows`"),
        "namespace_rename_base": ("A", "W `captured_namespace_states.rs::a_moved_base_directory_has_no_row_and_no_value`"),
        "namespace_generation": ("A", "W `namespace_view.rs::known_install_folds_a_capture_and_keeps_later_namespace_changes`"),
        "namespace_notification_failure": ("C", "[D4]"),
    },
    "tests/open.rs": {
        "open_permissions": ("A", "W `native_visit.rs::a_visit_through_a_read_only_descriptor_is_refused_and_changes_nothing`, D `native_mutation.rs` (`refusals`)"),
        "open_modes": ("A", "W `native_visit.rs::an_open_visit_decides_a_regular_file_and_records_its_descriptor_alone`"),
        "open_capacity": ("C", "[D8] (128 handles)"),
        "open_last_slot": ("C", "[D8]"),
        "open_metadata_failure": ("C", "[D3]"),
        "open_forget": ("A", "D `native_custody.rs::kernel_forget_arrives_on_a_live_connection_with_its_exact_decrement`, D `mounted_drain.rs::fp31_batched_forget_is_exact_and_outstanding_lookups_retire_in_bounded_turns_after_detach`"),
        "open_deadline": ("C", "[D5]"),
        "open_successor": ("A", "D `mounted_install.rs::retained_descriptors_and_kernel_caches_are_unchanged_by_install`"),
    },
    "tests/payload.rs": {
        "private_payload_profile_explicitly_requires_linux": ("C", "[D3]"),
        "linux_owned_payload_contract": ("A+C", "[D3]. O `payload.rs` (4), W `payload.rs` (4)"),
    },
    "tests/pieces_sequence.rs": "ALL_C_D3",
    "tests/prepared_namespace.rs": _all(
        "a_wide_directory_lowers_to_its_exact_rows_and_one_head a_wide_name_pass_over_one_identity_reads_each_path_once a_prepared_update_past_the_metadata_frame_travels_as_a_stream",
        "A+C", "Prepared stream [D9]. W `captured_namespace_cursor.rs` (3), D `mounted_install.rs::a_directory_of_more_than_one_name_window_is_listed`"),
    "tests/readable.rs": {
        "immutable_reads_handles_eof_and_terminal_failure": ("A", "W `base.rs::full_root_binding_aliases_metadata_symlinks_and_eof_use_content_apis`"),
        "directory_cookies_are_stable_and_bound_to_handles": ("A", "W `native_directory.rs::empty_whiteout_pages_continue_and_only_accepted_names_become_resume_cookies`, D `mounted_rewind.rs`"),
        "mount_lease_reply_ownership_admission_and_clean_close": ("A+C", "Separate close [D6]. D `native_mount.rs::ready_mount_serves_the_complete_root_to_unregistered_access_then_drains`"),
        "branch_symlink_permission_and_failed_attach_are_explicit": ("A", "D `native_mount.rs::attach_refusals_have_no_effect_and_a_failed_attach_returns_to_unattached`"),
        "full_cookie_table_still_replays_existing_positions": ("A+C", "Fixed cookie table [D8]. D `directory_cost.rs::a_rewound_handle_stores_one_listing_and_refuses_the_offsets_it_gave_before`"),
        "root_owner_reads_mode_zero_but_execute_requires_an_execute_bit": ("B", "Execute permission on a mounted file. **Migrated**: D `mounted_execute.rs::a_stored_program_executes_and_its_in_place_rewrite_executes_next` (added in this stage; Linux receipt `execute-attempt1-linux-mounted_execute.txt`)"),
        "detach_waits_for_projection_handles_and_preserves_local_handles": ("A", "D `mounted_drain.rs::fp21_a_parked_release_keeps_unmount_draining_until_its_credits_return_inside_the_window`, D `forced_unmount.rs::fp33_a_held_descriptor_leaves_the_mount_aborted_and_retained`"),
        "registry_grows_on_demand_and_keeps_retained_capacity_charged": ("C", "[D3] [D8]"),
        "failed_close_keeps_its_registry_count_until_cleanup_succeeds": ("A+C", "[D6]. D `native_custody.rs::an_unmount_that_cannot_revoke_stops_retained_and_later_replies_repeat_it`"),
        "readonly_component_chain_retains_all_270_forgotten_ancestors": ("A", "W `native_directory.rs::opened_directory_retains_parent_and_metadata_after_forget_and_rmdir`, O `native_lookup.rs` (10)"),
    },
    "tests/resize.rs": {
        "resize_semantics": ("A", "W `payload.rs::truncate_and_regrow_never_resurrect_bytes_across_capture_and_known_install`"),
        "resize_envelope": ("C", "[D8] (8 MiB zero-extension envelope)"),
        "resize_successor": ("A", "W `captured_namespace_fragments.rs::shrinking_and_regrowing_across_cells_never_returns_cut_bytes`"),
        "resize_overwritten_zero": ("A", "W `captured_namespace_fragments.rs::a_hole_and_written_zeros_are_the_same_bytes`"),
        "resize_metadata_only": ("A", "W `captured_namespace_states.rs::a_base_file_with_only_metadata_changes_keeps_its_content_root`"),
        "resize_refusals": ("A", "W `native_visit.rs::a_visit_through_a_read_only_descriptor_is_refused_and_changes_nothing`"),
        "resize_metadata_failure": ("C", "[D3]"),
        "resize_native_save": ("A", "D `captured_commit.rs::every_kind_of_change_commits_through_the_driver_and_reads_back_from_a_fresh_bind`"),
        "resize_frontier": ("A", "W `captured_namespace_fragments.rs::a_truncate_between_pieces_cuts_what_was_written_before_it`"),
    },
    "tests/stage.rs": {
        "stage_semantics": ("A+C", "Separate staging [D7]. D `store_commit.rs::committed_up_to_date_overwrite_and_new_bind_preserve_exact_roots`"),
        "stage_native_save": ("A", "D `captured_commit.rs::every_kind_of_change_commits_through_the_driver_and_reads_back_from_a_fresh_bind`"),
        "stage_unknown_save": ("A", "D `store_commit.rs::nested_storage_unknown_keeps_original_capture_and_blocks_another_commit`"),
        "stage_metadata_denied": ("C", "[D1]"),
        "stage_lowering": ("A+C", "[D9]. W `captured_namespace.rs` (9)"),
        "stage_head_moved": ("C", "[D7]"),
        "stage_frontier": ("A", "D `captured_commit.rs::mutations_after_the_capture_stay_out_of_its_root_and_survive_install`"),
        "stage_completion_failure": ("A", "D `captured_commit.rs::a_failed_attempt_keeps_its_custody_publishes_nothing_and_a_later_commit_is_exact`"),
        "stage_metadata_only": ("A", "W `captured_namespace_states.rs::link_count_changes_alone_keep_content_and_metadata_roots`"),
        "stage_headroom": ("C", "[D3] [D12]"),
    },
    "tests/symlink.rs": {
        "symlink_semantics": ("A", "W `namespace.rs::create_mkdir_symlink_and_link_publish_parent_and_reference_effects_atomically`, W `nonfile.rs` (3)"),
        "symlink_successor": ("A", "W `captured_namespace_states.rs::a_fresh_symlink_takes_exactly_its_captured_target`"),
        "symlink_capacity": ("C", "[D3] [D8]"),
        "symlink_refusals": ("A", "W `namespace.rs::unrepresentable_names_targets_and_reservations_are_refused_before_any_job`"),
        "symlink_backing_failure": ("C", "[D3]"),
        "symlink_reserve_denied": ("A+C", "[D1]. D `mounted_failure_scope.rs::a_create_with_no_serial_range_under_a_held_store_writer_is_eagain_with_no_effect`"),
        "symlink_reserve_unknown": ("A+C", "[D1]. same"),
    },
    "tests/wide_namespace.rs": {
        "one_directory_accepts_many_names_and_survives_rename_and_removal": ("A", "W `namespace_view.rs::name_and_inode_counts_have_no_cap_and_every_window_stays_bounded`"),
        "one_unlink_of_a_wide_directory_rewrites_one_path": ("A+C", "Tree path rewrite [D3]. W `native_unlink_cost.rs::one_removed_file_costs_exactly_this_beside_any_files_and_after_any_orphans`"),
        "a_generation_admits_many_identities_while_its_budget_has_room": ("C", "[D3] [D8]"),
        "create_cost_by_64_public_calls": ("A", "W `native_visit_cost.rs::the_five_jobs_of_one_created_file_cost_exactly_this_at_any_directory_size`"),
        "a_spent_budget_refuses_precisely_and_publishes_nothing": ("C", "[D3] [D8]"),
    },
    "tests/write.rs": {
        "write_positional": ("A", "W `payload.rs::writes_change_only_their_window_and_never_read_the_inherited_payload`"),
        "write_append": ("A", "W `namespace_daemon.rs::concurrent_appenders_and_a_tail_reader_see_whole_records_through_real_owner_jobs`"),
        "write_zero_rights": ("A", "W `native_visit.rs::a_visit_through_a_read_only_descriptor_is_refused_and_changes_nothing`"),
        "write_envelope": ("C", "[D8] (per-write envelope cap)"),
        "write_frontier": ("A", "W `captured_namespace_fragments.rs::pieces_crossing_the_end_of_a_base_file_give_one_root`"),
        "write_quota": ("A+C", "[D12]. O `device_capacity.rs`, D `device_capacity.rs`"),
        "write_metadata_failure": ("C", "[D3]"),
        "write_released": ("A", "W `captured_namespace_holds.rs::a_file_created_held_written_unlinked_and_written_again_is_never_constructed`, W `namespace_daemon_cases/orphans.rs` (2)"),
        "write_deadline": ("C", "[D5]"),
        "write_pending": ("C", "[D5] (reply permit)"),
        "write_successor": ("A", "D `store_commit.rs::later_mutation_survives_capture_publication_and_known_install`"),
        "write_native_save": ("A", "D `captured_commit.rs::every_kind_of_change_commits_through_the_driver_and_reads_back_from_a_fresh_bind`"),
    },
}
WS_OTHER = {
    "Cargo.toml": ("C", "Depends on the active `layerfs-bridge` and `layerfs-fuse`, whose APIs it does not match; cannot be loaded"),
    "tests/*.py (24 files)": ("C", "Docker route drivers and fixture preparation for the tests above; none is referenced outside this crate"),
    "tests/support/native_workspace.rs": ("C", "Fixture over the host Service [D1]"),
    "tests/support/prepared.rs": ("C", "Prepared-stream helpers [D9]"),
    "tests/store_lock.c": ("C", "Observer of the host Store lock for the Docker drivers [D1]"),
}
