[package]
name = "layerfs-metadata"
description = "PostgreSQL storage metadata and history engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-storage = { path = "../layerfs-storage" }
layerfs-history = { path = "../layerfs-history", default-features = false }
layerfs-content = { path = "../layerfs-content" }
postgres = "=0.19.14"
postgres-native-tls = "=0.5.3"
native-tls = "=0.2.18"
tokio-postgres = "=0.7.18"
tokio = { version = "=1.53.2", features = ["rt", "net", "time", "io-util"] }

[dev-dependencies]
blake3 = { version = "=1.8.5", default-features = false }
tokio-native-tls = "=0.3.1"
