[package]
name = "layerfs-workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-branch-store = { path = "../layerfs-branch-store" }
layerfs-core = { path = "../layerfs-core" }
layerfs-storage-core = { path = "../layerfs-storage-core" }

[lib]
path = "src/lib.rs"

[dev-dependencies]
layerfs-layer-store = { path = "../layerfs-layer-store" }
