[package]
name = "layerfs-os"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-engine = { path = "../layerfs-engine" }
layerfs-vfs = { path = "../layerfs-vfs" }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "=0.2.189"

[lib]
path = "src/lib.rs"
