[package]
name = "layerfs-working-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
test-hooks = ["layerfs-storage/test-hooks"]

[dependencies]
layerfs-core = { path = "../layerfs-core" }
layerfs-storage = { path = "../layerfs-storage" }

[lib]
path = "src/lib.rs"
