import type { FilesystemSQLiteDriver, FilesystemSQLiteTransaction, SqliteRow } from "../sqlite-driver.js";
import type { RuntimeLimits, StorageLimits } from "../resources/limits.js";
import { runUnitOfWork } from "../sqlite/unit-of-work.js";
import { ContentRepository } from "../sqlite/content-repository.js";
import { decodeManifestNode, decodeManifestRoot } from "../manifests/codec.js";
import { bytesToHex, hexToBytes } from "../utils/bytes.js";
import type { FilesystemMaintenance, GarbageCollectionOptions, GarbageCollectionResult, StorageSnapshot, VerificationOptions, VerificationResult, VerificationScope } from "../filesystem/types.js";
import { abortError, fsError } from "../filesystem/errors.js";

interface RunRow extends SqliteRow { id: string; state: number; high_water: number; root_generation: number; examined_roots: number; deleted_roots: number; examined_nodes: number; deleted_nodes: number; examined_objects: number; deleted_objects: number; reclaimed_object_bytes: number; reclaimed_manifest_bytes: number }
interface MarkRow extends SqliteRow { kind: number; hash: Uint8Array }
interface PayloadRow extends SqliteRow { hash: Uint8Array; size: number; allocation_sequence: number }
interface UsageRow extends SqliteRow { object_count: number; object_bytes: number; manifest_root_count: number; manifest_root_bytes: number; manifest_node_count: number; manifest_node_bytes: number; page_bytes: number; patch_bytes: number; charged_metadata_bytes: number }
interface SnapshotRow extends UsageRow { generation: number; logical_bytes: number; revisions: number }
interface ScalarRow extends SqliteRow { value: number }
interface HashRow extends SqliteRow { hash: Uint8Array; encoded: Uint8Array }
interface InodeVerifyRow extends SqliteRow { id: string; type: number; size: number | null; manifest_hash: Uint8Array | null; nlink: number; actual_links: number }

const COMPLETE = 4; const ABANDONED = 5;

export class MaintenanceManager implements FilesystemMaintenance {
  readonly #driver: FilesystemSQLiteDriver; readonly #storage: StorageLimits; readonly #runtime: RuntimeLimits; readonly #clock: () => number;
  constructor(driver: FilesystemSQLiteDriver, storage: StorageLimits, runtime: RuntimeLimits, clock: () => number) { this.#driver = driver; this.#storage = storage; this.#runtime = runtime; this.#clock = clock; }

  async collectGarbage(options: GarbageCollectionOptions = {}): Promise<GarbageCollectionResult> {
    if (this.#driver.readOnly) throw fsError("EROFS", "collectGarbage", undefined, "garbage collection requires writable storage"); if (options.signal?.aborted) throw abortError();
    const start = performance.now(); const runId = options.runId ?? globalThis.crypto.randomUUID(); const maxBatches = options.maxBatches ?? 100_000; if (!Number.isSafeInteger(maxBatches) || maxBatches < 0) throw fsError("EINVAL", "collectGarbage", undefined, "maxBatches must be a nonnegative safe integer");
    this.#write((tx) => { const existing = this.#run(tx, runId); if (existing) return; tx.run("DELETE FROM efs_leases WHERE expires_at_ms<?", [this.#now()]); const meta = tx.all<{ next_allocation_sequence: number; root_mutation_generation: number } & SqliteRow>("SELECT next_allocation_sequence,root_mutation_generation FROM efs_meta WHERE singleton=1", [], { maxRows: 1, maxBytes: 1024 })[0]!; tx.run("INSERT INTO efs_gc_runs(id,state,high_water,root_generation,cursor_kind,cursor_value,created_at_ms) VALUES(?,0,?,?,0,NULL,?)", [runId, meta.next_allocation_sequence - 1, meta.root_mutation_generation, this.#now()]); this.#addRoots(tx, runId); });
    let batches = 0;
    try {
      while (batches < maxBatches) {
        if (options.signal?.aborted) throw abortError(); const state = this.#read((tx) => this.#run(tx, runId)?.state); if (state === undefined) throw fsError("ENOENT", "collectGarbage", undefined, "collection run does not exist"); if (state === COMPLETE || state === ABANDONED) break;
        if (state === 0) this.#markBatch(runId); else this.#sweepBatch(runId, state); batches += 1;
      }
    } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) { try { this.#write((tx) => tx.run("UPDATE efs_gc_runs SET state=? WHERE id=? AND state<>?", [ABANDONED, runId, COMPLETE])); } catch {} } throw error; }
    const row = this.#read((tx) => this.#run(tx, runId)); if (!row) throw fsError("ENOENT", "collectGarbage", undefined, "collection run disappeared");
    return Object.freeze({ runId, state: row.state === COMPLETE ? "complete" : row.state === ABANDONED ? "abandoned" : "paused", examinedManifestRootCount: row.examined_roots, deletedManifestRootCount: row.deleted_roots, examinedManifestNodeCount: row.examined_nodes, deletedManifestNodeCount: row.deleted_nodes, examinedManifestCount: row.examined_roots + row.examined_nodes, deletedManifestCount: row.deleted_roots + row.deleted_nodes, examinedObjectCount: row.examined_objects, deletedObjectCount: row.deleted_objects, reclaimedObjectPayloadBytes: row.reclaimed_object_bytes, reclaimedManifestPayloadBytes: row.reclaimed_manifest_bytes, reclaimedBranchOverlayPayloadBytes: 0, committedBatches: batches, elapsedMs: performance.now() - start });
  }

  async snapshotStorage(): Promise<StorageSnapshot> {
    const row = this.#read((tx) => tx.all<SnapshotRow>("SELECT u.object_count,u.object_bytes,u.manifest_root_count,u.manifest_root_bytes,u.manifest_node_count,u.manifest_node_bytes,u.page_bytes,u.patch_bytes,u.charged_metadata_bytes,m.root_mutation_generation generation,(SELECT coalesce(sum(size),0) FROM efs_inodes WHERE type=0) logical_bytes,(SELECT count(*) FROM efs_revisions) revisions FROM efs_usage u JOIN efs_meta m ON m.singleton=u.singleton", [], { maxRows: 1, maxBytes: 4096 })[0]); if (!row) throw new Error("ECORRUPT: usage metadata is missing");
    const physical = this.#read((tx) => { const pageCount = this.#scalar(tx, "SELECT page_count value FROM pragma_page_count"); const pageSize = this.#scalar(tx, "SELECT page_size value FROM pragma_page_size"); const free = this.#scalar(tx, "SELECT freelist_count value FROM pragma_freelist_count"); return Object.freeze({ mainFileBytes: pageCount * pageSize, freelistBytes: free * pageSize }); });
    const manifestBytes = row.manifest_root_bytes + row.manifest_node_bytes;
    return Object.freeze({ rootMutationGeneration: row.generation, mainLogicalBytes: row.logical_bytes, storedObjectPayloadBytes: row.object_bytes, storedManifestPayloadBytes: manifestBytes, reachableObjectPayloadBytes: row.object_bytes, reachableManifestPayloadBytes: manifestBytes, reclaimablePayloadBytes: 0, branchPageBytes: row.page_bytes, branchPatchBytes: row.patch_bytes, branchExclusiveObjectBytes: 0, branchExclusiveManifestBytes: 0, branchExclusivePayloadBytes: row.page_bytes + row.patch_bytes, objectCount: row.object_count, manifestRootCount: row.manifest_root_count, manifestNodeCount: row.manifest_node_count, manifestCount: row.manifest_root_count + row.manifest_node_count, chargedMetadataBytes: row.charged_metadata_bytes, revisionCount: row.revisions, includesNamespaceMetadata: true, includesOperationResults: true, physical });
  }

  async verify(options: VerificationOptions = {}): Promise<VerificationResult> {
    if (options.signal?.aborted) throw abortError(); const maximum = options.maxEntities ?? this.#storage.maxGcBatchSize; if (!Number.isSafeInteger(maximum) || maximum <= 0) throw fsError("EINVAL", "verify", undefined, "maxEntities must be a positive safe integer"); const scopes = new Set<VerificationScope>(options.scopes ?? ["metadata", "namespace", "manifests", "objects", "head"]); const phases = ["roots", "nodes", "objects", "inodes"] as const; let cursor = options.cursor ? this.#decodeCursor(options.cursor) : { phase: 0, last: "" }; let checked = 0;
    const generation = this.#read((tx) => {
      const result = this.#scalar(tx, "SELECT root_mutation_generation value FROM efs_meta WHERE singleton=1"); const repo = new ContentRepository(tx, this.#storage);
      while (checked < maximum && cursor.phase < phases.length) {
        const phase = phases[cursor.phase]!; if ((phase === "roots" || phase === "nodes") && !scopes.has("manifests") || phase === "objects" && !scopes.has("objects") || phase === "inodes" && !scopes.has("namespace") && !scopes.has("head")) { cursor = { phase: cursor.phase + 1, last: "" }; continue; }
        if (phase === "roots" || phase === "nodes") { const table = phase === "roots" ? "efs_manifest_roots" : "efs_manifest_nodes"; const rows = tx.all<HashRow>(`SELECT hash,encoded FROM ${table} WHERE hash>? ORDER BY hash LIMIT ?`, [cursor.last ? hexToBytes(cursor.last, 32) : new Uint8Array(), maximum - checked], { maxRows: maximum - checked, maxBytes: this.#runtime.maxQueryBatchBytes }); for (const row of rows) { if (phase === "roots") decodeManifestRoot(row.encoded, row.hash); else decodeManifestNode(row.encoded, row.hash); cursor.last = bytesToHex(row.hash); checked += 1; } if (rows.length < maximum - (checked - rows.length)) cursor = { phase: cursor.phase + 1, last: "" }; else break; }
        else if (phase === "objects") { const rows = tx.all<PayloadRow>("SELECT hash,size,allocation_sequence FROM efs_cas_objects WHERE hash>? ORDER BY hash LIMIT ?", [cursor.last ? hexToBytes(cursor.last, 32) : new Uint8Array(), maximum - checked], { maxRows: maximum - checked, maxBytes: this.#runtime.maxQueryBatchBytes }); for (const row of rows) { const object = repo.getObject(row.hash); if (!object || object.byteLength !== row.size) throw new Error("ECORRUPT: invalid CAS object"); cursor.last = bytesToHex(row.hash); checked += 1; } if (rows.length < maximum - (checked - rows.length)) cursor = { phase: cursor.phase + 1, last: "" }; else break; }
        else { const rows = tx.all<InodeVerifyRow>("SELECT i.id,i.type,i.size,i.manifest_hash,i.nlink,(SELECT count(*) FROM efs_entries e WHERE e.inode_id=i.id) actual_links FROM efs_inodes i WHERE i.id>? ORDER BY i.id LIMIT ?", [cursor.last, maximum - checked], { maxRows: maximum - checked, maxBytes: this.#runtime.maxQueryBatchBytes }); for (const row of rows) { if (row.type === 0) { if (!row.manifest_hash || row.size === null) throw new Error("ECORRUPT: file inode lacks content"); const rootBytes = repo.getManifestRoot(row.manifest_hash); if (!rootBytes || decodeManifestRoot(rootBytes, row.manifest_hash).fileSize !== row.size) throw new Error("ECORRUPT: inode manifest size mismatch"); if (row.actual_links !== row.nlink) throw new Error("ECORRUPT: hard-link count mismatch"); } cursor.last = row.id; checked += 1; } if (rows.length < maximum - (checked - rows.length)) cursor = { phase: cursor.phase + 1, last: "" }; else break; }
      }
      return result;
    });
    return Object.freeze({ rootMutationGeneration: generation, checkedEntities: checked, complete: cursor.phase >= phases.length, nextCursor: cursor.phase >= phases.length ? null : this.#encodeCursor(cursor) });
  }

  #markBatch(runId: string): void { this.#write((tx) => { const run = this.#run(tx, runId)!; const perMark = 129; const limit = Math.max(1, Math.min(this.#storage.maxGcBatchSize, Math.floor(this.#storage.maxFinalTransactionRows / perMark))); const rows = tx.all<MarkRow>("SELECT kind,hash FROM efs_gc_marks WHERE run_id=? AND processed=0 ORDER BY kind,hash LIMIT ?", [runId, limit], { maxRows: limit, maxBytes: this.#runtime.maxQueryBatchBytes }); const repo = new ContentRepository(tx, this.#storage); let roots = 0; let nodes = 0; let objects = 0;
      for (const row of rows) { if (row.kind === 0) { const encoded = repo.getManifestRoot(row.hash); if (!encoded) throw new Error("ECORRUPT: reachable manifest root is missing"); const root = decodeManifestRoot(encoded, row.hash); tx.run("INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) VALUES(?,1,?,0)", [runId, root.rootNodeHash]); roots += 1; } else if (row.kind === 1) { const encoded = repo.getManifestNode(row.hash); if (!encoded) throw new Error("ECORRUPT: reachable manifest node is missing"); const node = decodeManifestNode(encoded, row.hash); if (node.kind === "leaf") for (const entry of node.entries) tx.run("INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) VALUES(?,2,?,0)", [runId, entry.hash]); else for (const child of node.children) tx.run("INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) VALUES(?,1,?,0)", [runId, child.hash]); nodes += 1; } else { if (!repo.getObject(row.hash)) throw new Error("ECORRUPT: reachable object is missing"); objects += 1; } tx.run("UPDATE efs_gc_marks SET processed=1 WHERE run_id=? AND kind=? AND hash=?", [runId, row.kind, row.hash]); }
      tx.run("UPDATE efs_gc_runs SET examined_roots=examined_roots+?,examined_nodes=examined_nodes+?,examined_objects=examined_objects+? WHERE id=?", [roots, nodes, objects, runId]);
      if (!rows.length) { const added = this.#addRoots(tx, runId); const generation = this.#scalar(tx, "SELECT root_mutation_generation value FROM efs_meta WHERE singleton=1"); tx.run("UPDATE efs_gc_runs SET root_generation=? WHERE id=?", [generation, runId]); if (!added) tx.run("UPDATE efs_gc_runs SET state=1 WHERE id=?", [runId]); }
    }); }
  #sweepBatch(runId: string, state: number): void { this.#write((tx) => { const run = this.#run(tx, runId)!; const table = state === 1 ? "efs_manifest_roots" : state === 2 ? "efs_manifest_nodes" : "efs_cas_objects"; const kind = state - 1; const rows = tx.all<PayloadRow>(`SELECT hash,${state === 3 ? "size" : "length(encoded)"} size,allocation_sequence FROM ${table} WHERE allocation_sequence<=? AND NOT EXISTS(SELECT 1 FROM efs_gc_marks m WHERE m.run_id=? AND m.kind=? AND m.hash=${table}.hash) ORDER BY allocation_sequence LIMIT ?`, [run.high_water, runId, kind, this.#storage.maxGcBatchSize], { maxRows: this.#storage.maxGcBatchSize, maxBytes: this.#runtime.maxQueryBatchBytes });
      let bytes = 0; for (const row of rows) { tx.run(`DELETE FROM ${table} WHERE hash=?`, [row.hash]); bytes += row.size; } if (rows.length) { const countColumn = state === 1 ? "manifest_root_count" : state === 2 ? "manifest_node_count" : "object_count"; const byteColumn = state === 1 ? "manifest_root_bytes" : state === 2 ? "manifest_node_bytes" : "object_bytes"; tx.run(`UPDATE efs_usage SET ${countColumn}=${countColumn}-?,${byteColumn}=${byteColumn}-?,charged_metadata_bytes=max(0,charged_metadata_bytes-?) WHERE singleton=1`, [rows.length, bytes, rows.length * 96]); tx.run(`UPDATE efs_gc_runs SET ${state === 1 ? "deleted_roots" : state === 2 ? "deleted_nodes" : "deleted_objects"}=${state === 1 ? "deleted_roots" : state === 2 ? "deleted_nodes" : "deleted_objects"}+?,${state === 3 ? "reclaimed_object_bytes" : "reclaimed_manifest_bytes"}=${state === 3 ? "reclaimed_object_bytes" : "reclaimed_manifest_bytes"}+? WHERE id=?`, [rows.length, bytes, runId]); } else { const next = state === 3 ? COMPLETE : state + 1; tx.run("UPDATE efs_gc_runs SET state=? WHERE id=?", [next, runId]); if (next === COMPLETE) { const generation = this.#scalar(tx, "SELECT root_mutation_generation value FROM efs_meta WHERE singleton=1"); tx.run("DELETE FROM efs_root_journal WHERE generation<?", [Math.max(0, generation - 10_000)]); } }
    }); }
  #addRoots(tx: FilesystemSQLiteTransaction, runId: string): number { let changes = 0; for (const sql of [
    "INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) SELECT ?,0,manifest_hash,0 FROM efs_inodes WHERE manifest_hash IS NOT NULL",
    "INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) SELECT ?,0,manifest_hash,0 FROM efs_revision_manifest_roots",
    "INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) SELECT ?,0,manifest_hash,0 FROM efs_branch_manifest_roots",
    "INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) SELECT ?,0,lm.manifest_hash,0 FROM efs_lease_manifests lm JOIN efs_leases l ON l.id=lm.lease_id",
    "INSERT OR IGNORE INTO efs_gc_marks(run_id,kind,hash,processed) SELECT ?,0,manifest_hash,0 FROM efs_staging_certificates WHERE sealed=1",
  ]) changes += tx.run(sql, [runId]).changes; return changes; }
  #run(tx: FilesystemSQLiteTransaction, id: string): RunRow | undefined { return tx.all<RunRow>("SELECT id,state,high_water,root_generation,examined_roots,deleted_roots,examined_nodes,deleted_nodes,examined_objects,deleted_objects,reclaimed_object_bytes,reclaimed_manifest_bytes FROM efs_gc_runs WHERE id=?", [id], { maxRows: 1, maxBytes: 4096 })[0]; }
  #scalar(tx: FilesystemSQLiteTransaction, sql: string): number { const value = tx.all<ScalarRow>(sql, [], { maxRows: 1, maxBytes: 1024 })[0]?.value; if (typeof value !== "number") throw new Error("ECORRUPT: invalid scalar"); return value; }
  #read<T>(callback: (tx: FilesystemSQLiteTransaction) => T): T { return runUnitOfWork(this.#driver, "read", { maxRows: this.#storage.maxFinalTransactionRows, maxBytes: this.#storage.maxFinalTransactionBytes }, callback); }
  #write<T>(callback: (tx: FilesystemSQLiteTransaction) => T): T { return runUnitOfWork(this.#driver, "write", { maxRows: this.#storage.maxFinalTransactionRows, maxBytes: this.#storage.maxFinalTransactionBytes }, callback); }
  #now(): number { return this.#clock(); }
  #encodeCursor(cursor: { phase: number; last: string }): string { return btoa(JSON.stringify(cursor)); }
  #decodeCursor(value: string): { phase: number; last: string } { try { const result = JSON.parse(atob(value)); if (!Number.isInteger(result.phase) || typeof result.last !== "string") throw new Error(); return result; } catch { throw fsError("EINVAL", "verify", undefined, "invalid verification cursor"); } }
}
