import hashlib,json,sqlite3,subprocess,shutil
from pathlib import Path
ROOT=Path.cwd();out=ROOT/'core/docs/issues/302/checks/sqlite-plan-profile1';source=ROOT/'benchmark-results/fs-bench-pro/issue302-unit-metadata-history157-candidate1/store.sqlite';copy=ROOT/'benchmark-results/fs-bench-pro/issue302-sqlite-plan-profile1/store.sqlite'
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
before=digest(source);copy.parent.mkdir(parents=True,exist_ok=False);shutil.copyfile(source,copy)
c=sqlite3.connect(f'file:{copy}?mode=ro',uri=True)
obj=c.execute('SELECT hex(object_id) FROM object_location ORDER BY object_id LIMIT 1').fetchone()[0];ordinal=c.execute('SELECT first_ordinal FROM metadata_value_group ORDER BY first_ordinal LIMIT 1').fetchone()[0]
queries={'mapping':('SELECT unit_id,group_number,offset,length FROM pack_unit WHERE pack_id=?1 ORDER BY group_number LIMIT 257',(1,)), 'control':('SELECT CASE WHEN length(control) BETWEEN 24 AND ?2 THEN control END AS control,pack_id,domain,digest,length,length(control) FROM pack WHERE pack_id=?1',(1,4120)), 'locator':('SELECT o.object_id,o.role,o.canonical_length,o.group_number,o.record_number,p.pack_id,p.domain,p.digest,p.length FROM object_location o JOIN pack p ON p.pack_id=o.pack_id WHERE o.object_id IN(?)',(bytes.fromhex(obj),)), 'metadata':('WITH wanted(ordinal) AS(VALUES (?)),covering AS(SELECT ordinal,(SELECT first_ordinal FROM metadata_value_group WHERE first_ordinal<=w.ordinal ORDER BY first_ordinal DESC LIMIT 1) first FROM wanted w) SELECT DISTINCT g.first_ordinal,g.count,g.pack_id,g.group_number,g.digest FROM covering c JOIN metadata_value_group g ON g.first_ordinal=c.first WHERE c.ordinal<g.first_ordinal+g.count ORDER BY g.first_ordinal',(ordinal,)), 'unit_insert':('INSERT INTO pack_unit(pack_id,group_number,offset,length,body) VALUES(?,?,?,?,?)',(1,0,24,1,b'x')), 'begin':('BEGIN',()), 'commit':('COMMIT',())}
plans={name:{'sql':sql,'bindings':[v.hex() if isinstance(v,bytes) else v for v in params],'eqp':c.execute('EXPLAIN QUERY PLAN '+sql,params).fetchall(),'explain':c.execute('EXPLAIN '+sql,params).fetchall()} for name,(sql,params) in queries.items()}
card=c.execute('SELECT n,count(*) FROM (SELECT count(*) n FROM pack_unit GROUP BY pack_id) GROUP BY n').fetchall();c.close()
def profile(name):
 p=subprocess.run([str(copy.parent/'unit-profile'),str(copy)],capture_output=True,text=True);(out/(name+'.stderr')).write_text(p.stderr);(out/(name+'.stdout')).write_text(p.stdout);p.check_returncode();return json.loads(p.stdout)
original=profile('original')
c=sqlite3.connect(copy);c.execute('CREATE INDEX diagnostic_pack_unit_cover ON pack_unit(pack_id,group_number,offset,length)');c.commit();coverplan={'eqp':c.execute('EXPLAIN QUERY PLAN '+queries['mapping'][0],(1,)).fetchall(),'explain':c.execute('EXPLAIN '+queries['mapping'][0],(1,)).fetchall()};index_pages=c.execute("SELECT count(*),sum(pgsize),sum(payload) FROM dbstat WHERE name='diagnostic_pack_unit_cover'").fetchone();c.close();cover=profile('covering')
result={'status':'PASS','kind':'read-only-plan-and-owned-copy-count-cause','source_sha256':before,'source_preserved':digest(source)==before,'sqlite_python':sqlite3.sqlite_version,'plans':plans,'covering_plan':coverplan,'cardinality':card,'original':original,'covering':cover,'additional_index_pages_bytes_payload':index_pages,'omissions':['No cold product latency claim','No actual gate publication/storage qualification','No retained Store mutation','One traversal per distinct pack, not history access-frequency replay']};(out/'diagnostic.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({k:v for k,v in result.items() if k not in ('plans','covering_plan','cardinality')},indent=2));print('mapping plan',plans['mapping']['eqp']);print('covering plan',coverplan['eqp']);print('metadata plan',plans['metadata']['eqp'])
