import type { FilesystemSQLiteDriver, FilesystemSQLiteTransaction, SqliteRow } from "../sqlite-driver.js";
import { buildManifest } from "../manifests/builder.js";
import { DEFAULT_FASTCDC } from "../cdc/fastcdc.js";
import { ContentRepository } from "../sqlite/content-repository.js";
import { initializeOrValidateSchema } from "../sqlite/schema.js";
import { runUnitOfWork } from "../sqlite/unit-of-work.js";
import { DEFAULT_FILESYSTEM_LIMITS, DEFAULT_RUNTIME_LIMITS, constrainStorageLimits, resolveLimits, type FilesystemLimits, type RuntimeLimits, type StorageLimits } from "../resources/limits.js";
import { NamespaceRepository, type InodeRow } from "../namespace/repository.js";
import { canonicalizePath, type CanonicalPath } from "../namespace/paths.js";
import { readManifestInto, readManifestRange } from "../operations/manifest-io.js";
import type { DirectoryEntry, FileStat, StorageFormatOptions } from "../filesystem/types.js";
import { fsError } from "../filesystem/errors.js";
import { utf8 } from "../utils/bytes.js";

interface ChildRow extends SqliteRow { name: string; type: number }
interface CountRow extends SqliteRow { count: number }
export interface SyncPreparedContent { readonly manifestHash: Uint8Array; readonly size: number }
export interface CreateNodeVfsBridgeOptions { readonly database: FilesystemSQLiteDriver; readonly filesystem?: Partial<FilesystemLimits>; readonly storage?: Partial<StorageLimits>; readonly runtime?: Partial<RuntimeLimits>; readonly format?: StorageFormatOptions; readonly clock?: () => number }
export interface NodeVfsFilesystemBridge {
  readonly filesystemLimits: Readonly<FilesystemLimits>; readonly storageLimits: Readonly<StorageLimits>; readonly runtimeLimits: Readonly<RuntimeLimits>; readonly cowPageBytes: 4096 | 8192 | 16384;
  existsSync(path: string): boolean; statSync(path: string, followFinal?: boolean): FileStat; readdirSync(path: string): DirectoryEntry[]; readlinkSync(path: string): string;
  readIntoSync(path: string, destination: Uint8Array, destinationOffset: number, position: number, length: number): number; readRangeSync(path: string, position: number, length: number): Uint8Array; readFileSync(path: string): Uint8Array;
  prepareContentSync(bytes: Uint8Array): SyncPreparedContent; readPreparedIntoSync(prepared: SyncPreparedContent, destination: Uint8Array, destinationOffset: number, position: number, length: number): number;
  commitPreparedSync(path: string, prepared: SyncPreparedContent, options?: { create?: boolean; exclusive?: boolean; mode?: number }): void; writeFileSync(path: string, bytes: Uint8Array, options?: { create?: boolean; exclusive?: boolean; mode?: number }): void;
  mkdirSync(path: string, options?: { recursive?: boolean; mode?: number }): void; chmodSync(path: string, mode: number): void; linkSync(existingPath: string, newPath: string): void; symlinkSync(target: string, path: string): void; renameSync(oldPath: string, newPath: string): void; unlinkSync(path: string): void; rmdirSync(path: string): void;
}

function kind(value: number): "file" | "directory" | "symlink" { return value === 0 ? "file" : value === 1 ? "directory" : value === 2 ? "symlink" : (() => { throw new Error("ECORRUPT: invalid inode type"); })(); }
function stat(inode: InodeRow, name: string): FileStat { const type = kind(inode.type); const size = type === "file" ? inode.size! : type === "symlink" ? utf8(inode.symlink_target ?? "").length : 0; return Object.freeze({ id: inode.id, name, type, mode: inode.mode, size, nlink: inode.nlink, mtimeMs: inode.mtime_ms, ctimeMs: inode.ctime_ms, birthtimeMs: inode.birthtime_ms, isFile: () => type === "file", isDirectory: () => type === "directory", isSymbolicLink: () => type === "symlink" }); }

class Bridge implements NodeVfsFilesystemBridge {
  readonly filesystemLimits: Readonly<FilesystemLimits>; readonly storageLimits: Readonly<StorageLimits>; readonly runtimeLimits: Readonly<RuntimeLimits>; readonly cowPageBytes: 4096 | 8192 | 16384;
  readonly #driver: FilesystemSQLiteDriver; readonly #clock: () => number;
  constructor(options: CreateNodeVfsBridgeOptions) { this.#driver = options.database; this.#clock = options.clock ?? Date.now; this.filesystemLimits = resolveLimits(DEFAULT_FILESYSTEM_LIMITS, options.filesystem); this.storageLimits = constrainStorageLimits(options.storage, options.database.capabilities); this.runtimeLimits = resolveLimits(DEFAULT_RUNTIME_LIMITS, options.runtime); this.cowPageBytes = initializeOrValidateSchema(options.database, { ...(options.format?.cowPageBytes === undefined ? {} : { cowPageBytes: options.format.cowPageBytes }), now: this.#now() }).cowPageBytes; }
  existsSync(path: string): boolean { try { this.statSync(path); return true; } catch (error) { if (error instanceof Error && "code" in error && error.code === "ENOENT") return false; throw error; } }
  statSync(path: string, followFinal = true): FileStat { const canonical = canonicalizePath(path, this.filesystemLimits, "statSync"); return this.#read((tx) => { const value = new NamespaceRepository(tx, this.filesystemLimits, "statSync").resolve(canonical, followFinal); return stat(value.inode, canonical.segments.at(-1) ?? ""); }); }
  readdirSync(path: string): DirectoryEntry[] { const canonical = canonicalizePath(path, this.filesystemLimits, "readdirSync"); return this.#read((tx) => { const selected = new NamespaceRepository(tx, this.filesystemLimits, "readdirSync").resolve(canonical, true); if (selected.inode.type !== 1) throw fsError("ENOTDIR", "readdirSync", canonical.value, "path is not a directory"); const rows = tx.all<ChildRow>("SELECT e.name,i.type FROM efs_entries e JOIN efs_inodes i ON i.id=e.inode_id WHERE e.parent_inode=? AND e.inode_id IS NOT NULL ORDER BY e.name_sort", [selected.inode.id], { maxRows: this.filesystemLimits.maxReaddirEntries, maxBytes: this.runtimeLimits.maxQueryBatchBytes }); return rows.map((row) => { const type = kind(row.type); return Object.freeze({ name: row.name, parentPath: canonical.value, type, isFile: () => type === "file", isDirectory: () => type === "directory", isSymbolicLink: () => type === "symlink" }); }); }); }
  readlinkSync(path: string): string { const canonical = canonicalizePath(path, this.filesystemLimits, "readlinkSync"); return this.#read((tx) => { const value = new NamespaceRepository(tx, this.filesystemLimits, "readlinkSync").resolve(canonical, false); if (value.inode.type !== 2 || value.inode.symlink_target === null) throw fsError("EINVAL", "readlinkSync", canonical.value, "path is not a symbolic link"); return value.inode.symlink_target; }); }
  readIntoSync(path: string, destination: Uint8Array, destinationOffset: number, position: number, length: number): number { const canonical = canonicalizePath(path, this.filesystemLimits, "readIntoSync"); return this.#read((tx) => { const inode = new NamespaceRepository(tx, this.filesystemLimits, "readIntoSync").resolve(canonical, true).inode; if (inode.type !== 0 || !inode.manifest_hash) throw fsError(inode.type === 1 ? "EISDIR" : "EINVAL", "readIntoSync", canonical.value, "path is not a file"); return readManifestInto(new ContentRepository(tx, this.storageLimits), inode.manifest_hash, position, destination, destinationOffset, length); }); }
  readRangeSync(path: string, position: number, length: number): Uint8Array { const output = new Uint8Array(length); const read = this.readIntoSync(path, output, 0, position, length); return read === length ? output : output.slice(0, read); }
  readFileSync(path: string): Uint8Array { const size = this.statSync(path).size; if (size > this.runtimeLimits.maxManagedResidentBytes) throw fsError("EFBIG", "readFileSync", path, "file exceeds synchronous materialization limit"); return this.readRangeSync(path, 0, size); }
  prepareContentSync(bytes: Uint8Array): SyncPreparedContent { const manifest = buildManifest(bytes, DEFAULT_FASTCDC); for (const [hash, object] of manifest.objects) this.#write((tx) => new ContentRepository(tx, this.storageLimits).putObject(BufferlessHex(hash), object)); for (const node of manifest.nodes.values()) this.#write((tx) => new ContentRepository(tx, this.storageLimits).putManifestNode(node.hash, node.encoded)); this.#write((tx) => new ContentRepository(tx, this.storageLimits).putManifestRoot(manifest.rootHash, manifest.root)); return Object.freeze({ manifestHash: manifest.rootHash, size: bytes.length }); }
  readPreparedIntoSync(prepared: SyncPreparedContent, destination: Uint8Array, destinationOffset: number, position: number, length: number): number { return this.#read((tx) => readManifestInto(new ContentRepository(tx, this.storageLimits), prepared.manifestHash, position, destination, destinationOffset, length)); }
  commitPreparedSync(path: string, prepared: SyncPreparedContent, options: { create?: boolean; exclusive?: boolean; mode?: number } = {}): void { const canonical = canonicalizePath(path, this.filesystemLimits, "commitVisibleSync"); if (canonical.value === "/") throw fsError("EISDIR", "commitVisibleSync", canonical.value, "root is a directory"); this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "commitVisibleSync"); const existing = ns.resolveOptional(canonical, true); if (options.exclusive && existing) throw fsError("EEXIST", "commitVisibleSync", canonical.value, "destination exists"); if (!existing && options.create === false) throw fsError("ENOENT", "commitVisibleSync", canonical.value, "file does not exist"); if (existing?.inode.type === 1) throw fsError("EISDIR", "commitVisibleSync", canonical.value, "destination is a directory"); const now = this.#now(); const revision = ns.nextRevision(now, existing ? 1 : 3, "node-vfs"); if (existing) { tx.run("UPDATE efs_inodes SET size=?,manifest_hash=?,mtime_ms=max(mtime_ms,?),ctime_ms=max(ctime_ms,?),token=? WHERE id=?", [prepared.size, prepared.manifestHash, now, now, revision, existing.inode.id]); ns.recordInode(revision, existing.inode.id); } else { const parent = ns.resolveParent(canonical); const id = globalThis.crypto.randomUUID(); tx.run("INSERT INTO efs_inodes(id,type,mode,birthtime_ms,mtime_ms,ctime_ms,nlink,size,manifest_hash,symlink_target,token) VALUES(?,0,?,?,?,?,1,?,?,NULL,?)", [id, (options.mode ?? 0o666) & 0o7777, now, now, now, prepared.size, prepared.manifestHash, revision]); ns.putEntry(parent.parent.inode.id, parent.nameSort, parent.name, id, revision); ns.recordEntry(revision, parent.parent.inode.id, parent.nameSort); ns.recordInode(revision, id); this.#touch(tx, ns, parent.parent.inode, now, revision); } }); }
  writeFileSync(path: string, bytes: Uint8Array, options?: { create?: boolean; exclusive?: boolean; mode?: number }): void { this.commitPreparedSync(path, this.prepareContentSync(bytes), options); }
  mkdirSync(path: string, options: { recursive?: boolean; mode?: number } = {}): void { const canonical = canonicalizePath(path, this.filesystemLimits, "mkdirSync"); if (canonical.value === "/") { if (options.recursive) return; throw fsError("EEXIST", "mkdirSync", canonical.value, "root exists"); } this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "mkdirSync"); if (ns.resolveOptional(canonical, false)) { if (options.recursive) return; throw fsError("EEXIST", "mkdirSync", canonical.value, "destination exists"); } const prefixes = options.recursive ? canonical.segments.map((_, index) => `/${canonical.segments.slice(0, index + 1).join("/")}`) : [canonical.value]; const now = this.#now(); let revision: number | undefined; for (const prefix of prefixes) { if (ns.resolveOptional(prefix, false)) continue; const current = canonicalizePath(prefix, this.filesystemLimits, "mkdirSync"); const parent = ns.resolveParent(current); revision ??= ns.nextRevision(now, prefixes.length * 3, "node-vfs"); const id = globalThis.crypto.randomUUID(); tx.run("INSERT INTO efs_inodes(id,type,mode,birthtime_ms,mtime_ms,ctime_ms,nlink,size,manifest_hash,symlink_target,token) VALUES(?,1,?,?,?,?,1,NULL,NULL,NULL,?)", [id, (options.mode ?? 0o777) & 0o7777, now, now, now, revision]); ns.putEntry(parent.parent.inode.id, parent.nameSort, parent.name, id, revision); ns.recordEntry(revision, parent.parent.inode.id, parent.nameSort); ns.recordInode(revision, id); this.#touch(tx, ns, parent.parent.inode, now, revision); } }); }
  chmodSync(path: string, mode: number): void { this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "chmodSync"); const value = ns.resolve(path, true); const now = this.#now(); const revision = ns.nextRevision(now, 1, "node-vfs"); tx.run("UPDATE efs_inodes SET mode=?,ctime_ms=max(ctime_ms,?),token=? WHERE id=?", [mode & 0o7777, now, revision, value.inode.id]); ns.recordInode(revision, value.inode.id); }); }
  linkSync(existingPath: string, newPath: string): void { this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "linkSync"); const source = ns.resolve(existingPath, true); if (source.inode.type !== 0) throw fsError("EPERM", "linkSync", existingPath, "only files can be hard linked"); const destination = canonicalizePath(newPath, this.filesystemLimits, "linkSync"); if (ns.resolveOptional(destination, false)) throw fsError("EEXIST", "linkSync", destination.value, "destination exists"); const parent = ns.resolveParent(destination); const now = this.#now(); const revision = ns.nextRevision(now, 3, "node-vfs"); ns.putEntry(parent.parent.inode.id, parent.nameSort, parent.name, source.inode.id, revision); tx.run("UPDATE efs_inodes SET nlink=nlink+1,ctime_ms=max(ctime_ms,?),token=? WHERE id=?", [now, revision, source.inode.id]); ns.recordEntry(revision, parent.parent.inode.id, parent.nameSort); ns.recordInode(revision, source.inode.id); this.#touch(tx, ns, parent.parent.inode, now, revision); }); }
  symlinkSync(target: string, path: string): void { this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "symlinkSync"); const destination = canonicalizePath(path, this.filesystemLimits, "symlinkSync"); if (ns.resolveOptional(destination, false)) throw fsError("EEXIST", "symlinkSync", destination.value, "destination exists"); const parent = ns.resolveParent(destination); const now = this.#now(); const revision = ns.nextRevision(now, 3, "node-vfs"); const id = globalThis.crypto.randomUUID(); tx.run("INSERT INTO efs_inodes(id,type,mode,birthtime_ms,mtime_ms,ctime_ms,nlink,size,manifest_hash,symlink_target,token) VALUES(?,2,511,?,?,?,1,NULL,NULL,?,?)", [id, now, now, now, target, revision]); ns.putEntry(parent.parent.inode.id, parent.nameSort, parent.name, id, revision); ns.recordEntry(revision, parent.parent.inode.id, parent.nameSort); ns.recordInode(revision, id); this.#touch(tx, ns, parent.parent.inode, now, revision); }); }
  renameSync(oldPath: string, newPath: string): void { const sourcePath = canonicalizePath(oldPath, this.filesystemLimits, "renameSync"); const destination = canonicalizePath(newPath, this.filesystemLimits, "renameSync"); if (sourcePath.value === destination.value) return; this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "renameSync"); const source = ns.resolve(sourcePath, false); const target = ns.resolveOptional(destination, false); if (target) this.#unlink(tx, ns, target.path, target.inode.type === 1, "renameSync"); const parent = ns.resolveParent(destination); const now = this.#now(); const revision = ns.nextRevision(now, 4, "node-vfs"); ns.putEntry(source.parentInode!, source.nameSort!, null, null, revision); ns.putEntry(parent.parent.inode.id, parent.nameSort, parent.name, source.inode.id, revision); ns.recordEntry(revision, source.parentInode!, source.nameSort!, true); ns.recordEntry(revision, parent.parent.inode.id, parent.nameSort); this.#touch(tx, ns, parent.parent.inode, now, revision); }); }
  unlinkSync(path: string): void { this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "unlinkSync"); const value = ns.resolve(path, false); if (value.inode.type === 1) throw fsError("EISDIR", "unlinkSync", path, "path is a directory"); this.#unlink(tx, ns, value.path, false, "unlinkSync"); }); }
  rmdirSync(path: string): void { this.#write((tx) => { const ns = new NamespaceRepository(tx, this.filesystemLimits, "rmdirSync"); const value = ns.resolve(path, false); if (value.inode.type !== 1) throw fsError("ENOTDIR", "rmdirSync", path, "path is not a directory"); if (tx.all<CountRow>("SELECT count(*) count FROM efs_entries WHERE parent_inode=? AND inode_id IS NOT NULL", [value.inode.id], { maxRows: 1, maxBytes: 100 })[0]!.count) throw fsError("ENOTEMPTY", "rmdirSync", path, "directory is not empty"); this.#unlink(tx, ns, value.path, true, "rmdirSync"); }); }
  #unlink(tx: FilesystemSQLiteTransaction, ns: NamespaceRepository, path: CanonicalPath, directory: boolean, syscall: string): void { const value = ns.resolve(path, false); const now = this.#now(); const revision = ns.nextRevision(now, 3, "node-vfs"); ns.putEntry(value.parentInode!, value.nameSort!, null, null, revision); ns.recordEntry(revision, value.parentInode!, value.nameSort!, true); if (!directory && value.inode.nlink > 1) { tx.run("UPDATE efs_inodes SET nlink=nlink-1,token=? WHERE id=?", [revision, value.inode.id]); ns.recordInode(revision, value.inode.id); } else { if (directory) tx.run("DELETE FROM efs_entries WHERE parent_inode=?", [value.inode.id]); tx.run("DELETE FROM efs_inodes WHERE id=?", [value.inode.id]); ns.recordInode(revision, value.inode.id, true); } }
  #touch(tx: FilesystemSQLiteTransaction, ns: NamespaceRepository, inode: InodeRow, now: number, revision: number): void { tx.run("UPDATE efs_inodes SET mtime_ms=max(mtime_ms,?),ctime_ms=max(ctime_ms,?),token=? WHERE id=?", [now, now, revision, inode.id]); ns.recordInode(revision, inode.id); }
  #read<T>(callback: (tx: FilesystemSQLiteTransaction) => T): T { return runUnitOfWork(this.#driver, "read", { maxRows: this.storageLimits.maxFinalTransactionRows, maxBytes: this.storageLimits.maxFinalTransactionBytes }, callback); }
  #write<T>(callback: (tx: FilesystemSQLiteTransaction) => T): T { return runUnitOfWork(this.#driver, "write", { maxRows: this.storageLimits.maxFinalTransactionRows, maxBytes: this.storageLimits.maxFinalTransactionBytes }, callback); }
  #now(): number { const now = this.#clock(); if (!Number.isSafeInteger(now) || now < 0) throw new Error("invalid clock"); return now; }
}

function BufferlessHex(value: string): Uint8Array { const bytes = new Uint8Array(32); for (let index = 0; index < 32; index += 1) bytes[index] = Number.parseInt(value.slice(index * 2, index * 2 + 2), 16); return bytes; }
export function createNodeVfsBridge(options: CreateNodeVfsBridgeOptions): NodeVfsFilesystemBridge { return new Bridge(options); }

