[package]
name = "layerfs-branch-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-content = { path = "../layerfs-content" }
layerfs-storage = { path = "../layerfs-storage" }

[dev-dependencies]
layerfs-layerstack-store = { path = "../layerfs-layerstack-store" }
rusqlite.workspace = true
