[package]
name = "layerfs-branch-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-content = { path = "../layerfs-content" }
layerfs-storage = { path = "../layerfs-storage" }

[dev-dependencies]
layerfs-layer-store = { path = "../layerfs-layer-store" }
layerfs-stack-store = { path = "../layerfs-stack-store" }
