[package]
name = "layerfs-branch-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-core = { path = "../layerfs-core" }
layerfs-storage-core = { path = "../layerfs-storage-core" }

[dev-dependencies]
layerfs-layer-store = { path = "../layerfs-layer-store" }
layerfs-stack-store = { path = "../layerfs-stack-store" }
