[package]
name = "layerfs-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-os = { path = "../layerfs-os" }
layerfs-vfs = { path = "../layerfs-vfs" }

[lib]
path = "src/lib.rs"

[dev-dependencies]
layerfs-core = { path = "../layerfs-core" }
layerfs-engine = { path = "../layerfs-engine" }
