[package]
name = "layerfs-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
test-hooks = ["layerfs-materialization/test-hooks", "layerfs-workspace/test-hooks"]

[dependencies]
layerfs-core = { path = "../layerfs-core" }
layerfs-materialization = { path = "../layerfs-materialization" }
layerfs-sync = { path = "../layerfs-sync" }
layerfs-working-store = { path = "../layerfs-working-store" }
layerfs-workspace = { path = "../layerfs-workspace" }

[lib]
path = "src/lib.rs"

[dev-dependencies]
layerfs-service = { path = "../layerfs-service" }
