//! External bounded inputs/output barriers for the actual public native route.
use layerfs_bridge::contract::{Source, FRAME_BYTES};
use std::{
    io::{self, Read, Write},
    sync::{
        atomic::{AtomicBool, Ordering},
        mpsc,
    },
    time::{Duration, Instant},
};

pub const DATA_BYTES: u64 = 32 * 1024 * 1024;
pub const DEADLINE_MS: u32 = 5000;
pub const STACK_BYTES: usize = 2 * 1024 * 1024;
pub fn expected(offset: u64) -> u8 {
    (offset % 251) as u8
}

/// A descriptor and generated bytes, with no whole-input fixture Vec.
pub struct Generated {
    descriptor_at: usize,
    position: u64,
}
impl Generated {
    pub fn new() -> Self {
        Self {
            descriptor_at: 0,
            position: 0,
        }
    }
}
impl Read for Generated {
    fn read(&mut self, buffer: &mut [u8]) -> io::Result<usize> {
        if self.descriptor_at < 24 {
            let mut descriptor = [0; 24];
            descriptor[..8].copy_from_slice(&1u64.to_be_bytes());
            descriptor[16..].copy_from_slice(&DATA_BYTES.to_be_bytes());
            let n = buffer.len().min(24 - self.descriptor_at);
            buffer[..n].copy_from_slice(&descriptor[self.descriptor_at..self.descriptor_at + n]);
            self.descriptor_at += n;
            return Ok(n);
        }
        let n = buffer.len().min((DATA_BYTES - self.position) as usize);
        for (i, byte) in buffer[..n].iter_mut().enumerate() {
            *byte = expected(self.position + i as u64);
        }
        self.position += n as u64;
        Ok(n)
    }
}

pub struct SourceGate {
    body: io::Cursor<Vec<u8>>,
    ready: mpsc::Sender<()>,
    release: mpsc::Receiver<()>,
    first: bool,
    resumes: std::sync::Arc<std::sync::atomic::AtomicUsize>,
}
impl SourceGate {
    pub fn new(
        body: Vec<u8>,
        ready: mpsc::Sender<()>,
        release: mpsc::Receiver<()>,
        resumes: std::sync::Arc<std::sync::atomic::AtomicUsize>,
    ) -> Self {
        Self {
            body: io::Cursor::new(body),
            ready,
            release,
            first: true,
            resumes,
        }
    }
}
impl Source for SourceGate {
    fn read(
        &mut self,
        buffer: &mut [u8],
        deadline: Instant,
        cancel: &AtomicBool,
    ) -> io::Result<usize> {
        if self.first {
            self.first = false;
            self.ready.send(()).map_err(|_| io::ErrorKind::BrokenPipe)?;
            loop {
                if cancel.load(Ordering::Acquire) {
                    return Err(io::ErrorKind::ConnectionAborted.into());
                }
                let left = deadline
                    .checked_duration_since(Instant::now())
                    .ok_or(io::ErrorKind::TimedOut)?;
                match self
                    .release
                    .recv_timeout(left.min(Duration::from_millis(10)))
                {
                    Ok(()) => {
                        self.resumes.fetch_add(1, Ordering::AcqRel);
                        break;
                    }
                    Err(mpsc::RecvTimeoutError::Timeout) => {}
                    Err(mpsc::RecvTimeoutError::Disconnected) => {
                        return Err(io::ErrorKind::BrokenPipe.into())
                    }
                }
            }
        }
        if cancel.load(Ordering::Acquire) {
            return Err(io::ErrorKind::ConnectionAborted.into());
        }
        if Instant::now() >= deadline {
            return Err(io::ErrorKind::TimedOut.into());
        }
        self.body.read(buffer)
    }
}

/// Holds the first *decoded* native ResultData callback. This alone does not
/// establish a live Server reader: the owning test independently probes Capacity.
pub struct CheckedGate {
    pub position: u64,
    ready: mpsc::Sender<usize>,
    release: mpsc::Receiver<()>,
    deadline: Instant,
    first: bool,
}
impl CheckedGate {
    pub fn new(ready: mpsc::Sender<usize>, release: mpsc::Receiver<()>, deadline: Instant) -> Self {
        Self {
            position: 0,
            ready,
            release,
            deadline,
            first: true,
        }
    }
}
impl Write for CheckedGate {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        assert!(!buffer.is_empty() && buffer.len() <= FRAME_BYTES);
        for (i, byte) in buffer.iter().enumerate() {
            assert_eq!(*byte, expected(self.position + i as u64));
        }
        if self.first {
            self.first = false;
            self.ready
                .send(buffer.len())
                .map_err(|_| io::ErrorKind::BrokenPipe)?;
            self.release
                .recv_timeout(self.deadline.saturating_duration_since(Instant::now()))
                .map_err(|_| io::ErrorKind::TimedOut)?;
        }
        self.position += buffer.len() as u64;
        Ok(buffer.len())
    }
    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Count actual public Source callback termination, never an inferred Store outcome.
#[allow(dead_code)]
#[derive(Default)]
pub struct SourceEnd {
    pub reads: std::sync::atomic::AtomicUsize,
    pub closed: std::sync::atomic::AtomicUsize,
    pub cancelled: std::sync::atomic::AtomicUsize,
    pub deadline: std::sync::atomic::AtomicUsize,
    pub returned: std::sync::atomic::AtomicUsize,
}
#[allow(dead_code)]
pub struct TerminalSource {
    ready: mpsc::Sender<()>,
    input: std::os::unix::net::UnixStream,
    end: std::sync::Arc<SourceEnd>,
}
#[allow(dead_code)]
impl TerminalSource {
    pub fn new(
        ready: mpsc::Sender<()>,
        input: std::os::unix::net::UnixStream,
        end: std::sync::Arc<SourceEnd>,
    ) -> Self {
        Self { ready, input, end }
    }
}
impl Source for TerminalSource {
    fn read(
        &mut self,
        buffer: &mut [u8],
        deadline: Instant,
        cancel: &AtomicBool,
    ) -> io::Result<usize> {
        self.end.reads.fetch_add(1, Ordering::AcqRel);
        let _ = self.ready.send(());
        let mut pipe = layerfs_bridge::adapters::native::pipe::Pipe {
            fd: &self.input,
            deadline,
            cancel,
        };
        let result = Read::read(&mut pipe, buffer);
        if matches!(result, Ok(0)) {
            self.end.closed.fetch_add(1, Ordering::AcqRel);
        }
        if result.is_err() {
            if cancel.load(Ordering::Acquire) {
                self.end.cancelled.fetch_add(1, Ordering::AcqRel);
            } else if result
                .as_ref()
                .is_err_and(|e| e.kind() == io::ErrorKind::TimedOut)
            {
                self.end.deadline.fetch_add(1, Ordering::AcqRel);
            }
        }
        self.end.returned.fetch_add(1, Ordering::AcqRel);
        result
    }
}

/// One native decoded callback with a fixed negative-vector deadline.
#[allow(dead_code)]
#[derive(Default)]
pub struct OutputEnd {
    pub writes: std::sync::atomic::AtomicUsize,
    pub deadline: std::sync::atomic::AtomicUsize,
}
#[allow(dead_code)]
pub struct DeadlineOutput {
    ready: mpsc::Sender<usize>,
    held: mpsc::Receiver<()>,
    deadline: Instant,
    end: std::sync::Arc<OutputEnd>,
}
#[allow(dead_code)]
impl DeadlineOutput {
    pub fn new(
        ready: mpsc::Sender<usize>,
        held: mpsc::Receiver<()>,
        deadline: Instant,
        end: std::sync::Arc<OutputEnd>,
    ) -> Self {
        Self {
            ready,
            held,
            deadline,
            end,
        }
    }
}
impl Write for DeadlineOutput {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        self.end.writes.fetch_add(1, Ordering::AcqRel);
        assert!(!buffer.is_empty() && buffer.len() <= FRAME_BYTES);
        for (i, byte) in buffer.iter().enumerate() {
            assert_eq!(*byte, expected(i as u64));
        }
        self.ready
            .send(buffer.len())
            .map_err(|_| io::ErrorKind::BrokenPipe)?;
        match self
            .held
            .recv_timeout(self.deadline.saturating_duration_since(Instant::now()))
        {
            Err(mpsc::RecvTimeoutError::Timeout) => {
                self.end.deadline.fetch_add(1, Ordering::AcqRel);
                Err(io::ErrorKind::TimedOut.into())
            }
            _ => Err(io::ErrorKind::BrokenPipe.into()),
        }
    }
    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Real tiny public Service output that retains exactly one operation permit.
#[allow(dead_code)]
pub struct TinyOutput {
    ready: mpsc::Sender<()>,
    release: mpsc::Receiver<()>,
    pub bytes: usize,
}
#[allow(dead_code)]
impl TinyOutput {
    pub fn new(ready: mpsc::Sender<()>, release: mpsc::Receiver<()>) -> Self {
        Self {
            ready,
            release,
            bytes: 0,
        }
    }
}
impl Write for TinyOutput {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        assert_eq!(buffer, [expected(0)]);
        assert_eq!(self.bytes, 0);
        self.ready.send(()).map_err(|_| io::ErrorKind::BrokenPipe)?;
        self.release
            .recv_timeout(Duration::from_secs(1))
            .map_err(|_| io::ErrorKind::TimedOut)?;
        self.bytes += buffer.len();
        Ok(buffer.len())
    }
    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}
