[package]
name = "layerfs-monitor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-layerstack-store = { path = "../layerfs-layerstack-store" }
layerfs-workspace = { path = "../layerfs-workspace" }

[dev-dependencies]
layerfs-layerstack-store = { path = "../layerfs-layerstack-store", features = ["test-instrumentation"] }
