//! Shared bounded update/resynchronization limits.

use super::MAXIMUM_CHUNK_BYTES;

pub const MAX_UPDATE_ANCHOR_SCAN_BYTES: u64 = 65_536;
pub const MAX_UPDATE_REJOIN_VERIFICATION_BYTES: u64 = MAXIMUM_CHUNK_BYTES as u64;
pub const MAX_UPDATE_RESYNCHRONIZATION_BYTES: u64 =
    MAX_UPDATE_ANCHOR_SCAN_BYTES + MAX_UPDATE_REJOIN_VERIFICATION_BYTES;
