[package]
name = "layerfs-durable-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
layerfs-core = { path = "../layerfs-core" }
layerfs-storage = { path = "../layerfs-storage" }

[target.'cfg(any(target_os = "android", target_os = "linux", target_vendor = "apple"))'.dependencies]
rustix = { version = "=1.1.4", features = ["fs"] }

[lib]
path = "src/lib.rs"

[dev-dependencies]
layerfs-working-store = { path = "../layerfs-working-store" }
